export const dom = {
  backendInput: document.getElementById("backend-url"),
  appSelect: document.getElementById("app-select"),
  refreshAppsButton: document.getElementById("refresh-apps"),
  conversationSelect: document.getElementById("conversation-select"),
  newConversationButton: document.getElementById("new-conversation"),
  conversationMeta: document.getElementById("conversation-meta"),
  conversationTimeline: document.getElementById("conversation-timeline"),
  requestTextInput: document.getElementById("request-text"),
  sendRequestButton: document.getElementById("send-request"),
  openAppButton: document.getElementById("open-app"),
  applyProposalButton: document.getElementById("apply-proposal"),
  autoOpenInput: document.getElementById("auto-open-app"),
  selectedAppUrl: document.getElementById("selected-app-url"),
  statusOutput: document.getElementById("status-output"),
  jobMeta: document.getElementById("job-meta"),
  jobPhase: document.getElementById("job-phase"),
  jobEvents: document.getElementById("job-events"),
  installButton: document.getElementById("install-button"),
  learningSummary: document.getElementById("learning-summary"),
  learningMeta: document.getElementById("learning-meta"),
};
