#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]


def read(relative_path: str) -> str:
    return (ROOT / relative_path).read_text(encoding="utf-8")


def require(content: str, needle: str, *, label: str) -> None:
    if needle not in content:
        raise AssertionError(f"missing {label}: {needle}")


def require_absent(content: str, needle: str, *, label: str) -> None:
    if needle in content:
        raise AssertionError(f"unexpected {label}: {needle}")


def main() -> int:
    app_js = read("examples/generated_apps/codex-ops-console/web/app.js")
    api_js = read("examples/generated_apps/codex-ops-console/web/ops-api.js")
    conversations_js = read("examples/generated_apps/codex-ops-console/web/ops-conversations.js")
    jobs_js = read("examples/generated_apps/codex-ops-console/web/ops-jobs.js")
    render_js = read("examples/generated_apps/codex-ops-console/web/ops-render.js")
    store_js = read("examples/generated_apps/codex-ops-console/web/ops-store.js")
    deployed_console_sh = read("scripts/verify_deployed_console.sh")
    deployed_workspace_py = read("scripts/verify_deployed_workspace_gate.py")
    styles_css = read("examples/generated_apps/codex-ops-console/web/styles.css")
    index_html = read("examples/generated_apps/codex-ops-console/web/index.html")
    autonomy_detail_index = index_html.index('id="autonomy-detail"')
    thread_scroller_index = index_html.index('id="thread-scroller"')
    footer_dock_index = index_html.index('id="conversation-footer-dock"')
    composer_shell_index = index_html.index('class="composer-shell"')
    session_strip_index = index_html.index('id="session-strip"')
    draft_status_index = index_html.index('id="draft-status"')
    composer_footer_index = index_html.index('class="composer-footer"')
    sidebar_index = index_html.index('id="nav-sheet"')
    main_stage_index = index_html.index('<section class="main-stage panel" data-primary-surface="conversation">')
    secondary_panel_index = index_html.index('id="secondary-panel"')
    if not (secondary_panel_index < autonomy_detail_index):
        raise AssertionError("detailed autonomy summary is no longer reachable through the secondary panel")
    if not (thread_scroller_index < footer_dock_index < composer_shell_index):
        raise AssertionError("footer dock does not wrap the session strip and composer after the thread scroller")
    if not (composer_shell_index < session_strip_index < draft_status_index < composer_footer_index):
        raise AssertionError("composer-adjacent activity bar no longer sits inside the composer shell ahead of footer actions")
    if not (sidebar_index < main_stage_index < secondary_panel_index):
        raise AssertionError("desktop workspace no longer uses sidebar, main stage, then secondary panel order")

    require(api_js, "/api/internal/conversations/${conversationId}/append-stream", label="append SSE URL builder")
    require(conversations_js, "new window.EventSource(internalConversationAppendStreamUrl(conversationId))", label="EventSource wiring")
    require(conversations_js, 'addEventListener("conversation.append"', label="append event listener")
    require(conversations_js, "appendEnvelope.conversation_id !== activeConversationId", label="cross-conversation guard")
    require(conversations_js, "appendId <= Number(state.appendStream?.lastAppendId || 0)", label="append_id dedupe")
    require(conversations_js, 'state.appendStream.status = "connecting"', label="connecting state")
    require(conversations_js, 'state.appendStream.status = "live"', label="live state")
    require(conversations_js, 'state.appendStream.status = "reconnecting"', label="reconnecting state")
    require(conversations_js, 'delivery_source: "sse"', label="SSE provenance tagging")
    require(conversations_js, "state.appendStream.transport = \"sse\"", label="SSE transport evidence")
    require(conversations_js, "syncConversationCardState", label="conversation card state sync helper")
    require(conversations_js, "showPendingOutgoing", label="pending outgoing render helper")
    require(conversations_js, "clearPendingOutgoing", label="pending outgoing clear helper")
    require(conversations_js, "showPendingAssistant", label="pending assistant handoff helper")
    require(conversations_js, "shouldClearPendingOutgoing", label="pending handoff clear predicate")
    require(conversations_js, "data-conversation-live-state", label="conversation card live state marker")
    require(conversations_js, "conversationPreview", label="conversation preview helper")
    require(conversations_js, "truncatePreview", label="bounded conversation preview helper")
    require(conversations_js, "latestMessagePreview", label="preferred message preview helper")
    require(conversations_js, "eventPreview", label="event preview helper")
    require(conversations_js, "snapshotThreadState", label="conversation snapshot state helper")
    require(conversations_js, "snapshotThreadLabel", label="conversation snapshot label helper")
    require(conversations_js, "compactConversationLabel", label="conversation live label helper")
    require(conversations_js, "liveOwnerLabel", label="selected live owner label helper")
    require(conversations_js, "data-conversation-session", label="conversation session marker DOM")
    require(conversations_js, "data-snapshot-thread-state", label="conversation snapshot state DOM")
    require(conversations_js, "data-snapshot-state-label", label="conversation snapshot state label DOM")
    require(conversations_js, 'data-preview-lines="1"', label="single-line conversation preview DOM")
    require(conversations_js, "dom.threadScroller?.dataset.sessionPresentation", label="left rail uses session presentation state")
    require(conversations_js, 'marker.textContent = isSelected && isLiveOwner ? "LIVE" : "NOW";', label="selected live owner marker label")
    require(conversations_js, "sessionMarker.hidden = !isSelected", label="selected thread session marker visibility")
    require(conversations_js, 'card.dataset.liveOwner = isSelected && isLiveOwner ? "true" : "false";', label="selected live owner dataset")
    require(conversations_js, "liveState.hidden = isSelected", label="selected thread snapshot badge hiding")
    require(conversations_js, 'return "CONNECT";', label="compact connecting rail label")
    require(conversations_js, 'return "RESUME";', label="compact reconnect rail label")
    require(conversations_js, 'return "LIVE";', label="compact live rail label")
    require(conversations_js, 'return "FAILED";', label="compact failed rail label")
    require(conversations_js, 'return "READY";', label="compact ready rail label")
    require(conversations_js, 'return "VERIFY";', label="compact verify rail label")
    require(conversations_js, 'return "REVIEW";', label="compact review rail label")
    require(conversations_js, 'return "DONE";', label="compact done rail label")
    require(conversations_js, 'return "IDLE";', label="compact idle rail label")
    require(jobs_js, "!isAppendStreamConnected(state, state.currentConversationId)", label="polling refetch skip while connected")
    require(render_js, "deriveLiveRunState", label="inline live run state derivation")
    require(render_js, 'state: "sending"', label="local pending sending state")
    require(render_js, 'state: "generating"', label="assistant placeholder generating state")
    require(render_js, 'state: "proposal-phase"', label="proposal phase live run state")
    require(render_js, 'state: "review-phase"', label="review phase live run state")
    require(render_js, 'state: "verify-phase"', label="verify phase live run state")
    require(render_js, 'state: "proposal-ready"', label="proposal ready live run state")
    require(render_js, 'state: "auto-apply"', label="auto-apply live run state")
    require(render_js, 'state: "applied"', label="applied live run state")
    require(render_js, 'phase: "PROPOSAL"', label="proposal phase label")
    require(render_js, 'phase: "REVIEW"', label="review phase label")
    require(render_js, 'phase: "VERIFY"', label="verify phase label")
    require(render_js, 'phase: "READY"', label="proposal ready phase label")
    require(render_js, 'phase: "APPLIED"', label="applied phase label")
    require(render_js, 'goal.proposal.phase.started', label="proposal phase event mapping")
    require(render_js, 'goal.review.phase.started', label="review phase event mapping")
    require(render_js, 'goal.verify.phase.started', label="verify phase event mapping")
    require(render_js, 'goal.proposal.auto_apply.started', label="auto-apply event mapping")
    require(render_js, "renderSessionStrip", label="unified session strip renderer")
    require(render_js, 'presentation === "sending"', label="sending presentation state")
    require(render_js, 'data-pending-local="true"', label="pending local timeline marker")
    require(render_js, 'data-pending-assistant="true"', label="pending assistant timeline marker")
    require(render_js, "local-pending", label="pending local render source")
    require(render_js, "local-assistant-placeholder", label="assistant placeholder render source")
    require(render_js, "pendingHandoffState", label="single pending handoff render helper")
    require(render_js, 'stage: "pending-user"', label="pending user handoff stage")
    require(render_js, 'stage: "pending-assistant"', label="pending assistant handoff stage")
    require(render_js, "pendingUserCount", label="pending user count dataset state")
    require(render_js, "pendingAssistantCount", label="pending assistant count dataset state")
    require(render_js, "handoffState.items", label="single pending handoff item render wiring")
    require(render_js, 'dom.threadScroller.dataset.pendingHandoffStage = handoffState.stage', label="pending handoff stage dataset")
    require(render_js, 'dom.threadScroller.dataset.pendingUserCount = String(handoffState.pendingUserCount)', label="pending user count dataset")
    require(render_js, 'dom.threadScroller.dataset.pendingAssistantCount = String(handoffState.pendingAssistantCount)', label="pending assistant count dataset")
    require(render_js, "autonomyDetailMeta", label="secondary panel autonomy detail meta wiring")
    require(render_js, "dataset.sessionPresentation", label="session strip presentation dataset")
    require(render_js, "dataset.sessionTerminal", label="session strip terminal dataset")
    require(render_js, "sessionRail", label="session rail local expansion state")
    require(render_js, "transportChip", label="composer state transport chip helper")
    require(render_js, "phaseChip", label="composer state phase chip helper")
    require(render_js, "proposalChip", label="composer state proposal chip helper")
    require(render_js, "phaseDetailHint", label="phase detail hint helper")
    require(render_js, "renderInlineSessionBlock", label="inline session workspace block helper")
    require(render_js, 'data-selected-thread-live-block="true"', label="inline session workspace block DOM")
    require(render_js, "renderTranscriptLiveActivity", label="transcript live activity helper")
    require(render_js, "transcriptLiveTone", label="transcript live activity tone helper")
    require(render_js, "composerActionHint", label="composer affordance hint helper")
    require(render_js, "threadMetaSummary", label="thread meta phase summary helper")
    require(render_js, "sessionProvenance", label="session provenance helper")
    require(render_js, "toggleSessionRail", label="session rail toggle helper")
    require(render_js, "dataset.sessionCollapsed", label="session strip collapsed dataset")
    require(render_js, "showComposerLiveStrip", label="composer live strip visibility guard")
    require(render_js, 'appendStream.transport === "sse"', label="composer live strip SSE transport guard")
    require(render_js, 'lastRenderSource === "sse"', label="composer live strip SSE render-source guard")
    require(render_js, 'dom.sessionStrip.hidden = !showComposerLiveStrip', label="composer live strip hidden when inactive")
    require(render_js, 'dom.sessionStrip.dataset.liveOwned = showComposerLiveStrip ? "true" : "false"', label="composer live strip ownership dataset")
    require(render_js, "session-chip", label="session chip render markup")
    require(render_js, "headerPhaseTone", label="thread header phase tone helper")
    require(render_js, "threadTitle", label="thread title header wiring")
    require(render_js, "threadPhaseChip", label="thread phase chip wiring")
    require(render_js, 'return { label: "SEND", tone: "thinking" };', label="compact send transport chip")
    require(render_js, 'return { label: "RECONNECT", tone: "warning" };', label="compact reconnect transport chip")
    require(render_js, 'return { label: "OPEN", tone: "neutral" };', label="compact connecting transport chip")
    require(render_js, 'return { label: "OFFLINE", tone: "danger" };', label="compact offline transport chip")
    require(render_js, 'return { label: "READY", tone: "healthy" };', label="compact ready chip")
    require(render_js, 'return { label: "APPLIED", tone: "healthy" };', label="compact applied chip")
    require(render_js, 'return { label: "BLOCKED", tone: "warning" };', label="compact blocked proposal chip")
    require(render_js, 'return "복구 중";', label="compact reconnect action hint")
    require(render_js, 'return "복구 필요";', label="compact offline action hint")
    require(render_js, 'return "연결 중";', label="compact connecting action hint")
    require(render_js, 'return "전송 중";', label="compact sending action hint")
    require(render_js, 'return "handoff 완료";', label="compact accepted action hint")
    require(render_js, 'return "bounded hypothesis 정리 중";', label="phase detail proposal hint")
    require(render_js, 'return "review 승인 신호 확인 중";', label="phase detail review hint")
    require(render_js, 'return "verify 결과 수집 중";', label="phase detail verify hint")
    require(render_js, 'return "승인 후 자동 적용 진행 중";', label="phase detail auto-apply hint")
    require(render_js, 'return "proposal 승인 또는 적용 대기";', label="phase detail proposal-ready hint")
    require(render_js, 'return "proposal 적용 반영 완료";', label="phase detail applied hint")
    require(render_js, 'return "응답 생성";', label="compact generating action hint")
    require(render_js, 'return "실행 중";', label="compact live execution action hint")
    require(render_js, 'return "계속 입력";', label="compact live action hint")
    require(render_js, 'return "입력 가능";', label="compact idle action hint")
    require(render_js, '"DEGRADED"', label="degraded stream provenance label")
    require(render_js, '"OFFLINE"', label="offline stream provenance label")
    require(render_js, 'dom.sessionStripToggle.hidden = true', label="session strip toggle hidden")
    require(render_js, 'dom.sendRequestButton.textContent = status === "live" || presentation === "sending" ? "추가 지시 보내기" : "메시지 보내기"', label="contextual send copy")
    require(render_js, 'dom.applyProposalButton.textContent = liveRun.state === "proposal-ready" ? "지금 제안 적용" : "제안 적용"', label="contextual apply copy")
    require(render_js, "dataset.liveRunState", label="live run state dataset")
    require(render_js, "dataset.liveRunPhase", label="live run phase dataset")
    require(render_js, "dataset.liveRunSource", label="live run source dataset")
    require(render_js, 'data-live-activity-turn="true"', label="transcript live activity DOM")
    require(render_js, 'data-append-source="sse-live-activity"', label="transcript live activity provenance DOM")
    require(render_js, "selected thread", label="transcript live activity selected-thread copy")
    require(render_js, 'transport !== "sse" || renderSource !== "sse"', label="transcript live activity SSE-only guard")
    require(render_js, "syncJumpToLatest", label="jump-to-latest sync helper")
    require(render_js, "updateLiveFollowFromScroll", label="live follow scroll helper")
    require(render_js, "jumpToLatest", label="jump-to-latest action helper")
    require(render_js, "currentState.liveFollow", label="live follow state wiring")
    require(render_js, "lastSeenAppendId", label="live follow seen append cursor")
    require(render_js, "followRenderSource", label="jump-to-latest render source dataset")
    require(render_js, "data-append-source", label="append provenance attribute")
    require(render_js, "dataset.streamState = status", label="stream-state dataset")
    require(render_js, "dataset.renderSource = lastRenderSource", label="render-source dataset")
    require(conversations_js, 'dom.threadScroller.dataset.pendingConversationId = conversationId', label="thread switch pending marker")
    require(conversations_js, "state.currentConversationId && state.currentConversationId !== conversationId", label="thread switch clear guard")
    require(store_js, "appendStream", label="append stream state")
    require(store_js, "pendingOutgoing", label="pending outgoing state")
    require(store_js, "assistantCreatedAt", label="assistant placeholder pending timestamp state")
    require(store_js, "baselineAppendId", label="pending handoff baseline append id state")
    require(store_js, "isAppendStreamConnected", label="append stream connection helper")
    require(store_js, "liveFollow", label="live follow state")
    require(store_js, "lastSeenAppendId", label="live follow seen append state")
    require(index_html, 'id="session-strip"', label="session strip DOM")
    require(index_html, 'id="session-strip-state"', label="session strip state DOM")
    require(index_html, 'id="session-strip-meta"', label="session strip meta DOM")
    require(index_html, 'id="session-strip-detail"', label="session strip detail DOM")
    require(index_html, 'data-thread-header="conversation"', label="conversation-first thread header DOM")
    require(index_html, 'id="thread-title"', label="thread title DOM")
    require(index_html, 'id="thread-phase-chip"', label="thread phase chip DOM")
    require(index_html, 'id="session-strip-toggle"', label="session strip toggle DOM")
    require(index_html, 'data-activity-bar="composer-adjacent"', label="composer-adjacent activity bar DOM")
    require(index_html, 'class="composer-toolbar"', label="chat-style composer toolbar DOM")
    require(index_html, 'class="composer-send-primary"', label="primary send button DOM")
    require(index_html, "composer-secondary-action", label="secondary composer action DOM")
    require(index_html, 'class="composer-utility-cluster"', label="composer utility cluster DOM")
    require(index_html, 'class="toggle inline composer-utility-toggle"', label="composer utility toggle DOM")
    require(index_html, 'id="conversation-footer-dock"', label="conversation footer dock DOM")
    require(index_html, 'data-footer-dock="session-composer"', label="footer dock mode DOM")
    require(index_html, 'data-session-workspace="conversation-first"', label="conversation-first session workspace DOM")
    require(index_html, 'id="jump-to-latest"', label="jump-to-latest DOM")
    require(index_html, 'id="autonomy-detail"', label="secondary panel autonomy detail DOM")
    require(index_html, 'id="autonomy-detail-meta"', label="secondary panel autonomy detail meta DOM")
    require(index_html, 'id="secondary-panel"', label="secondary panel DOM")
    require(index_html, 'data-secondary-panel-mode="compact-sidecar"', label="compact side panel DOM")
    require(index_html, 'id="secondary-panel-toggle"', label="secondary panel toggle DOM")
    require(index_html, 'id="secondary-panel-close"', label="secondary panel close DOM")
    require(index_html, 'id="nav-sheet-toggle"', label="mobile nav toggle DOM")
    require(index_html, 'id="nav-sheet-close"', label="mobile nav close DOM")
    require(index_html, 'id="nav-sheet-scrim"', label="mobile nav scrim DOM")
    require(index_html, 'id="nav-sheet"', label="mobile nav sheet DOM")
    require(index_html, 'data-mobile-surface="sheet"', label="mobile nav sheet surface marker")
    require(index_html, 'data-mobile-nav-priority="conversations"', label="mobile nav conversation priority DOM")
    require(index_html, 'data-nav-primary="threads"', label="mobile nav threads-first section DOM")
    require(index_html, 'data-nav-secondary="ops"', label="mobile nav secondary operator section DOM")
    require(index_html, 'data-primary-surface="conversation"', label="active conversation primary surface DOM")
    require(index_html, 'aria-controls="nav-sheet"', label="mobile nav toggle controls DOM")
    require(index_html, 'aria-expanded="false"', label="mobile nav closed default DOM")
    require(index_html, 'id="nav-ops-section"', label="mobile operator section DOM")
    require(index_html, 'id="nav-ops-summary"', label="mobile operator summary DOM")
    require(index_html, 'id="thread-scroller" class="thread-scroller" tabindex="-1"', label="conversation surface focus target DOM")
    require(app_js, "internalConversationAppendStreamUrl", label="controller dependency wiring")
    require(app_js, "showPendingOutgoing", label="pending outgoing submit wiring")
    require(app_js, "showPendingAssistant", label="pending assistant submit wiring")
    require(app_js, "clearPendingOutgoing", label="pending outgoing clear wiring")
    require(app_js, "setNavigationOpen", label="mobile nav state helper")
    require(app_js, "isPhoneViewport", label="phone breakpoint helper")
    require(app_js, "focusPrimaryNavAction", label="mobile nav primary action focus helper")
    require(app_js, "returnFocusToConversationSurface", label="mobile nav conversation return focus helper")
    require(app_js, "syncMobileWorkspaceMode", label="mobile nav mode helper")
    require(app_js, 'document.body.dataset.mobileNavMode = isPhoneViewport() ? "drawer" : "desktop"', label="mobile nav mode dataset")
    require(app_js, 'document.body.dataset.mobileWorkspace = isOpen ? "navigation" : "conversation"', label="mobile workspace state helper")
    require(app_js, 'dom.navOpsSection.open = false;', label="mobile operator section collapse on phone")
    require(app_js, 'dom.navSheetToggle.setAttribute("aria-expanded", isOpen ? "true" : "false")', label="mobile nav toggle expanded state")
    require(app_js, 'navSheet.setAttribute("aria-hidden", isOpen ? "false" : "true")', label="mobile nav sheet aria state")
    require(app_js, "syncNavOpsSection", label="mobile operator section state helper")
    require(app_js, "dom.navOpsSection.open = !isPhoneViewport();", label="mobile operator section breakpoint behavior")
    require(app_js, 'primaryAction.focus({ preventScroll: true })', label="mobile nav focuses first thread action")
    require(app_js, 'preferredTarget.focus({ preventScroll: true })', label="mobile conversation surface focus return")
    require(app_js, "updateLiveFollowFromScroll", label="live follow scroll event wiring")
    require(app_js, "jumpToLatest", label="jump-to-latest button wiring")
    require(app_js, "reengageLiveFollowFromComposer", label="composer reengages live follow helper")
    require(app_js, 'dom.requestTextInput.addEventListener("focus", reengageLiveFollowFromComposer)', label="composer focus reengages live follow")
    require(app_js, 'dom.requestTextInput.addEventListener("input", reengageLiveFollowFromComposer)', label="composer input reengages live follow")
    require(app_js, "toggleSessionRail", label="session rail toggle wiring")
    require(app_js, "setSecondaryPanelOpen", label="secondary panel state helper")
    require(app_js, 'window.innerWidth > 860', label="mobile nav resize reset")
    require(deployed_console_sh, 'WORKSPACE_APP_ID="${WORKSPACE_APP_ID:-factory-runtime}"', label="workspace gate app default")
    require(deployed_console_sh, 'python3 ./scripts/verify_deployed_workspace_gate.py', label="deployed workspace gate wiring")
    require(deployed_workspace_py, 'DEFAULT_REQUEST_TEXT = (', label="workspace gate default request")
    require(deployed_workspace_py, 'goal.proposal.phase.started', label="workspace gate proposal phase assertion")
    require(deployed_workspace_py, 'goal.review.phase.started', label="workspace gate review phase assertion")
    require(deployed_workspace_py, 'goal.verify.phase.started', label="workspace gate verify phase assertion")
    require(deployed_workspace_py, "proposal.ready", label="workspace gate proposal ready assertion")
    require(deployed_workspace_py, 'conversation.append', label="workspace gate sse append assertion")
    require(deployed_workspace_py, "phaseChip", label="workspace gate browser-visible phase chip assertion")
    require(deployed_workspace_py, "dataset.liveRunPhase", label="workspace gate live phase dataset assertion")
    require(deployed_workspace_py, "dataset.streamState", label="workspace gate transport dataset assertion")
    require(deployed_workspace_py, "unexpected session rotation", label="workspace gate session rotation guard")
    require(styles_css, 'body[data-nav-open="true"] .sidebar', label="mobile nav drawer CSS")
    require(styles_css, 'body[data-mobile-nav-mode="drawer"] .sidebar[data-mobile-nav-priority="conversations"] .sidebar-primary-nav', label="mobile nav drawer mode CSS")
    require(styles_css, 'body[data-mobile-workspace="conversation"] .main-stage', label="conversation-first mobile surface CSS")
    require(styles_css, "touch-action: none;", label="mobile nav open touch lock CSS")
    require(styles_css, 'body[data-secondary-panel-open="true"] .desktop-shell', label="desktop secondary panel layout CSS")
    require(styles_css, "grid-template-columns: 15rem minmax(0, 1fr);", label="desktop two-pane shell width")
    require(styles_css, "grid-template-columns: 13.5rem minmax(0, 1fr);", label="desktop two-pane shell width at medium desktop")
    require(styles_css, ".autonomy-detail-card", label="secondary panel autonomy detail card CSS")
    require(styles_css, ".secondary-panel", label="secondary panel CSS")
    require(styles_css, "position: fixed;", label="desktop secondary panel overlay positioning")
    require(styles_css, "width: min(18.5rem, calc(100vw - 2rem));", label="desktop secondary panel overlay width")
    require(styles_css, ".thread-title-row", label="thread title row CSS")
    require(styles_css, ".thread-phase-chip", label="thread phase chip CSS")
    require(styles_css, ".thread-sidecar", label="thread sidecar CSS")
    require(styles_css, "width: min(100%, 54rem);", label="dominant conversation column width")
    require(styles_css, ".conversation-card-live", label="conversation card live badge CSS")
    require(styles_css, ".conversation-card-marker", label="conversation card selected badge CSS")
    require(styles_css, ".conversation-card-session", label="conversation card session badge CSS")
    require(styles_css, '.conversation-card[data-live-owner="true"]', label="selected live owner card CSS")
    require(styles_css, ".conversation-card-tags", label="conversation card session tag row CSS")
    require(styles_css, ".conversation-card-preview", label="conversation card preview CSS")
    require(styles_css, '.conversation-card-preview[data-preview-lines="1"]', label="single-line conversation preview CSS")
    require(styles_css, '.conversation-card[data-thread-state="active"] .conversation-card-live', label="active card state CSS")
    require(styles_css, '.conversation-card[data-thread-state="active"] .conversation-card-session', label="active session marker CSS")
    require(styles_css, '.conversation-card[data-thread-state="review"] .conversation-card-live', label="review card state CSS")
    require(styles_css, '.conversation-card[data-thread-state="verify"] .conversation-card-live', label="verify card state CSS")
    require(styles_css, '.conversation-card[data-thread-state="ready"] .conversation-card-live', label="ready card state CSS")
    require(styles_css, '.conversation-card[data-live-owner="true"] .conversation-card-marker', label="selected live owner marker CSS")
    require(styles_css, '.conversation-card[data-live-owner="true"] .conversation-card-session', label="selected live owner session CSS")
    require(styles_css, '.conversation-card[data-thread-state="failed"] .conversation-card-live', label="failed card state CSS")
    require(styles_css, '.conversation-card[data-thread-state="idle"] .conversation-card-live', label="idle card state CSS")
    require(styles_css, ".timeline-item.message.user.pending-local", label="pending local message CSS")
    require(styles_css, ".timeline-item.message.assistant.pending-assistant", label="pending assistant message CSS")
    require(styles_css, ".timeline-item.live-activity", label="transcript live activity CSS")
    require(styles_css, ".session-inline-block", label="inline session block CSS")
    require(styles_css, ".session-inline-chip", label="inline session chip CSS")
    require(styles_css, ".session-inline-meta", label="inline session meta CSS")
    require(styles_css, ".timeline-live-row", label="transcript live activity chip row CSS")
    require(styles_css, ".timeline-live-chip", label="transcript live activity chip CSS")
    require(styles_css, ".session-strip", label="session strip CSS")
    require(styles_css, '.session-strip[data-live-owned="true"]', label="composer live strip active CSS")
    require(styles_css, ".session-activity-bar", label="composer activity bar CSS")
    require(styles_css, ".session-chip", label="composer state chip CSS")
    require(styles_css, "flex-wrap: wrap;", label="composer activity inline wrap CSS")
    require(styles_css, "justify-content: flex-start;", label="composer activity inline alignment CSS")
    require(styles_css, ".session-strip-toggle {\n  min-width: 5.8rem;\n  margin-left: auto;", label="composer activity toggle push CSS")
    require(styles_css, ".session-strip-meta,\n.session-strip-detail {\n  color: var(--muted);", label="composer activity inline metadata CSS")
    require(styles_css, "display: inline-flex;", label="composer activity inline chip display CSS")
    require_absent(styles_css, ".session-strip-main", label="legacy composer activity main CSS")
    require_absent(styles_css, ".session-strip-side", label="legacy composer activity side CSS")
    require(styles_css, ".session-strip-draft", label="composer activity draft CSS")
    require(styles_css, ".composer-toolbar", label="chat-style composer toolbar CSS")
    require(styles_css, ".composer-send-primary", label="primary send button CSS")
    require(styles_css, ".composer-secondary-action", label="secondary composer action CSS")
    require(styles_css, ".composer-utility-cluster", label="composer utility cluster CSS")
    require(styles_css, ".composer-utility-toggle", label="composer utility toggle CSS")
    require(styles_css, ".composer-hint-compact", label="compact composer hint CSS")
    require(styles_css, ".sidebar-primary-nav", label="mobile conversation-first nav section CSS")
    require(styles_css, ".sidebar-ops-details", label="mobile operator section CSS")
    require(styles_css, ".nav-ops-summary", label="mobile operator summary CSS")
    require(styles_css, ".nav-ops-content", label="mobile operator content CSS")
    require(styles_css, '.sidebar[data-mobile-nav-priority="conversations"] .sidebar-primary-nav[data-nav-primary="threads"]', label="mobile nav primary section priority CSS")
    require(styles_css, '.sidebar[data-mobile-nav-priority="conversations"] .sidebar-ops-details[data-nav-secondary="ops"]', label="mobile nav secondary section CSS")
    require(styles_css, ".sidebar-ops-details[open] .nav-ops-summary::after", label="mobile operator summary state CSS")
    require(styles_css, ".jump-to-latest", label="jump-to-latest CSS")
    require(styles_css, "position: sticky;", label="sticky footer CSS")
    require(styles_css, "env(safe-area-inset-bottom)", label="safe-area footer padding CSS")
    require(styles_css, ".mobile-nav-toggle", label="mobile nav button CSS")
    require(styles_css, ".thread-scroller:focus-visible", label="conversation surface focus ring CSS")
    require_absent(index_html, 'id="conversation-live-status"', label="legacy live badge DOM")
    require_absent(index_html, 'id="live-run-row"', label="legacy live run row DOM")
    require_absent(index_html, 'id="append-stream-strip"', label="legacy append stream DOM")
    require_absent(index_html, 'id="autonomy-context-strip"', label="header autonomy strip DOM")
    require_absent(index_html, 'id="hero-conversation-state"', label="header conversation status DOM")
    require_absent(index_html, 'id="hero-job-state"', label="header job status DOM")
    require_absent(index_html, 'id="hero-app-name"', label="legacy app-centric header title DOM")
    require_absent(index_html, "<h3>메시지 보내기</h3>", label="prose-heavy composer heading DOM")
    require_absent(index_html, "sidebar-inspector", label="legacy sidebar inspector")
    require_absent(index_html, "sidebar-footer", label="legacy sidebar footer")
    require_absent(index_html, 'class="autonomy-rail"', label="legacy standalone autonomy rail DOM")
    print("ok: ops desktop secondary panel, footer dock, session strip, append SSE wiring, and mobile nav drawer are present")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except AssertionError as error:
        print(f"verification failed: {error}", file=sys.stderr)
        raise SystemExit(1)
