#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]


def read(relative_path: str) -> str:
    return (ROOT / relative_path).read_text(encoding="utf-8")


def require(content: str, needle: str, *, label: str) -> None:
    if needle not in content:
        raise AssertionError(f"missing {label}: {needle}")


def require_absent(content: str, needle: str, *, label: str) -> None:
    if needle in content:
        raise AssertionError(f"unexpected {label}: {needle}")


def main() -> int:
    app_js = read("examples/generated_apps/codex-ops-console/web/app.js")
    api_js = read("examples/generated_apps/codex-ops-console/web/ops-api.js")
    conversations_js = read("examples/generated_apps/codex-ops-console/web/ops-conversations.js")
    jobs_js = read("examples/generated_apps/codex-ops-console/web/ops-jobs.js")
    render_js = read("examples/generated_apps/codex-ops-console/web/ops-render.js")
    store_js = read("examples/generated_apps/codex-ops-console/web/ops-store.js")
    deployed_console_sh = read("scripts/verify_deployed_console.sh")
    deployed_workspace_py = read("scripts/verify_deployed_workspace_gate.py")
    styles_css = read("examples/generated_apps/codex-ops-console/web/styles.css")
    index_html = read("examples/generated_apps/codex-ops-console/web/index.html")
    autonomy_detail_index = index_html.index('id="autonomy-detail"')
    recent_thread_rail_index = index_html.index('id="recent-thread-rail"')
    thread_scroller_index = index_html.index('id="thread-scroller"')
    footer_dock_index = index_html.index('id="conversation-footer-dock"')
    composer_shell_index = index_html.index('class="composer-shell"')
    session_strip_index = index_html.index('id="session-strip"')
    draft_status_index = index_html.index('id="draft-status"')
    composer_footer_index = index_html.index('class="composer-footer"')
    sidebar_index = index_html.index('id="nav-sheet"')
    main_stage_index = index_html.index('<section class="main-stage panel" data-primary-surface="conversation">')
    secondary_panel_index = index_html.index('id="secondary-panel"')
    if not (secondary_panel_index < autonomy_detail_index):
        raise AssertionError("detailed autonomy summary is no longer reachable through the secondary panel")
    if not (recent_thread_rail_index < thread_scroller_index < footer_dock_index < composer_shell_index):
        raise AssertionError("recent-thread rail, thread scroller, and footer dock order no longer preserves the conversation workspace")
    if not (composer_shell_index < session_strip_index < draft_status_index < composer_footer_index):
        raise AssertionError("composer-adjacent activity bar no longer sits inside the composer shell ahead of footer actions")
    if not (sidebar_index < main_stage_index < secondary_panel_index):
        raise AssertionError("desktop workspace no longer uses sidebar, main stage, then secondary panel order")

    require(api_js, "/api/internal/conversations/${conversationId}/append-stream", label="append SSE URL builder")
    require(conversations_js, "new window.EventSource(internalConversationAppendStreamUrl(conversationId))", label="EventSource wiring")
    require(conversations_js, 'addEventListener("conversation.append"', label="append event listener")
    require(conversations_js, "appendEnvelope.conversation_id !== activeConversationId", label="cross-conversation guard")
    require(conversations_js, "appendId <= Number(state.appendStream?.lastAppendId || 0)", label="append_id dedupe")
    require(conversations_js, 'state.appendStream.status = "connecting"', label="connecting state")
    require(conversations_js, 'state.appendStream.status = "live"', label="live state")
    require(conversations_js, 'state.appendStream.status = "reconnecting"', label="reconnecting state")
    require(conversations_js, 'delivery_source: "sse"', label="SSE provenance tagging")
    require(conversations_js, "state.appendStream.transport = \"sse\"", label="SSE transport evidence")
    require(conversations_js, "syncConversationCardState", label="conversation card state sync helper")
    require(conversations_js, "showPendingOutgoing", label="pending outgoing render helper")
    require(conversations_js, "clearPendingOutgoing", label="pending outgoing clear helper")
    require(conversations_js, "showPendingAssistant", label="pending assistant handoff helper")
    require(conversations_js, "shouldClearPendingOutgoing", label="pending handoff clear predicate")
    require(conversations_js, "data-conversation-live-state", label="conversation card live state marker")
    require(conversations_js, "conversationPreview", label="conversation preview helper")
    require(conversations_js, "truncatePreview", label="bounded conversation preview helper")
    require(conversations_js, "latestMessagePreview", label="preferred message preview helper")
    require(conversations_js, "eventPreview", label="event preview helper")
    require(conversations_js, "snapshotThreadState", label="conversation snapshot state helper")
    require(conversations_js, "snapshotThreadLabel", label="conversation snapshot label helper")
    require(conversations_js, "compactConversationLabel", label="conversation live label helper")
    require(conversations_js, "liveOwnerLabel", label="selected live owner label helper")
    require(conversations_js, "liveOwnerDetail", label="selected live owner detail helper")
    require(conversations_js, "liveOwnerFollowLabel", label="selected live owner follow helper")
    require(conversations_js, "liveOwnerState", label="selected live owner state helper")
    require(conversations_js, "liveOwnerMarkerLabel", label="selected live owner marker helper")
    require(conversations_js, "renderRecentThreadRail", label="recent-thread rail render helper")
    require(conversations_js, "RECENT_THREAD_LIMIT = 4", label="bounded recent-thread rail limit")
    require(conversations_js, "state.recentConversations = recentConversations.map", label="recent-thread state caching")
    require(conversations_js, "data-recent-thread-chip", label="recent-thread chip DOM")
    require(conversations_js, "data-recent-thread-marker", label="recent-thread marker DOM")
    require(conversations_js, "data-recent-thread-owner", label="recent-thread owner DOM")
    require(conversations_js, "data-recent-thread-state", label="recent-thread state DOM")
    require(conversations_js, "data-recent-thread-follow", label="recent-thread follow DOM")
    require(conversations_js, 'chip.dataset.liveOwner = isSelected && showLiveMirror ? "true" : "false";', label="recent-thread live owner dataset")
    require(conversations_js, 'stateLabel.textContent = isSwitching', label="recent-thread switching state wiring")
    require(conversations_js, 'follow.textContent = isSwitching ? "ATTACH" : isSelected && showLiveMirror ? liveFollowLabel : "";', label="recent-thread attach follow wiring")
    require(conversations_js, 'owner.textContent = "OWNER";', label="recent-thread owner label")
    require(conversations_js, "syncActiveSessionRow", label="sticky active session row helper")
    require(conversations_js, "threadTitleForConversation", label="thread switch title helper")
    require(conversations_js, "startThreadTransition", label="thread transition start helper")
    require(conversations_js, "clearThreadTransition", label="thread transition clear helper")
    require(conversations_js, 'state.currentConversationId = "";', label="thread switch clears current conversation before attach")
    require(conversations_js, "data-conversation-session", label="conversation session marker DOM")
    require(conversations_js, "data-conversation-live-owner-row", label="selected conversation live owner row DOM")
    require(conversations_js, "data-conversation-live-detail", label="selected conversation live detail DOM")
    require(conversations_js, "data-conversation-live-follow", label="selected conversation live follow DOM")
    require(conversations_js, "data-snapshot-thread-state", label="conversation snapshot state DOM")
    require(conversations_js, "data-snapshot-state-label", label="conversation snapshot state label DOM")
    require(conversations_js, 'data-preview-lines="1"', label="single-line conversation preview DOM")
    require(conversations_js, "dom.threadScroller?.dataset.sessionPresentation", label="left rail uses session presentation state")
    require(conversations_js, 'const selectedThreadSseOwned = selectedConversationId && selectedConversationId === liveConversationId && renderSource === "sse";', label="selected row sse ownership guard")
    require(conversations_js, 'marker.textContent = isSelected && showLiveMirror ? liveOwnerMarkerLabel(liveOwnerStateLabel) : "NOW";', label="selected live owner marker label")
    require(conversations_js, 'card.dataset.liveOwnerState = isSelected && showLiveMirror ? liveOwnerStateLabel : "idle";', label="selected live owner state dataset")
    require(conversations_js, 'liveDetailRow.dataset.liveOwnerState = isSelected && showLiveMirror ? liveOwnerStateLabel : "idle";', label="selected live owner row state dataset")
    require(conversations_js, 'liveFollowText.dataset.liveOwnerState = isSelected && showLiveMirror ? liveOwnerStateLabel : "idle";', label="selected live follow state dataset")
    require(conversations_js, "sessionMarker.hidden = !isSelected", label="selected thread session marker visibility")
    require(conversations_js, 'card.dataset.liveOwner = isSelected && showLiveMirror ? "true" : "false";', label="selected live owner dataset")
    require(conversations_js, "liveDetailRow.hidden = !(isSelected && showLiveMirror)", label="selected live detail visibility")
    require(conversations_js, "liveState.hidden = isSelected", label="selected thread snapshot badge hiding")
    require(conversations_js, 'dom.activeSessionRow.dataset.activeSessionState = visible ? rowState : "idle";', label="active session row state dataset")
    require(conversations_js, 'dom.activeSessionRow.dataset.activeSessionConversationId = visible ? conversationId : "";', label="active session row conversation dataset")
    require(conversations_js, 'dom.activeSessionRow.dataset.activeSessionFollow = visible ? followLabel.toLowerCase() : "idle";', label="active session row follow dataset")
    require(conversations_js, 'dom.activeSessionRow.dataset.activeSessionOwned = visible ? String(rowOwned) : "false";', label="active session row ownership dataset")
    require(conversations_js, 'dom.activeSessionRow.dataset.activeSessionSource = visible ? rowSource : "none";', label="active session row source dataset")
    require(conversations_js, 'dom.activeSessionRow.dataset.activeSessionPhase = visible ? rowPhase : "IDLE";', label="active session row phase dataset")
    require(conversations_js, 'dom.activeSessionRow.dataset.activeSessionUnseenCount = String(visible ? rowUnseenCount : 0);', label="active session row unseen dataset")
    require(conversations_js, 'stateLabel = "SWITCHING";', label="active session switching state label")
    require(conversations_js, 'followLabel = "ATTACH";', label="active session switching follow label")
    require(conversations_js, 'rowSource = "thread-transition";', label="active session switching source")
    require(conversations_js, 'rowSource = pendingStage === "pending-user" ? "local-handoff" : pendingStage === "pending-assistant" ? "selected-thread-handoff" : "selected-thread-sse";', label="active session selected-thread source")
    require(conversations_js, 'meta = `selected thread · ${rowUnseenCount} unseen live appends`;', label="active session unseen append copy")
    require(conversations_js, 'presentation === "live"', label="active session healthy live gate")
    require_absent(conversations_js, 'meta = "selected thread · reconnecting";', label="active session reconnecting copy")
    require(conversations_js, 'return "CONNECT";', label="compact connecting rail label")
    require(conversations_js, 'return "RESUME";', label="compact reconnect rail label")
    require(conversations_js, 'return "LIVE";', label="compact live rail label")
    require(conversations_js, 'return "FAILED";', label="compact failed rail label")
    require(conversations_js, 'return "READY";', label="compact ready rail label")
    require(conversations_js, 'return "VERIFY";', label="compact verify rail label")
    require(conversations_js, 'return "REVIEW";', label="compact review rail label")
    require(conversations_js, 'return "PROPOSAL";', label="compact proposal rail label")
    require(conversations_js, 'return "WAITING";', label="compact waiting rail label")
    require(conversations_js, 'return "ACTIVE";', label="compact active rail label")
    require(conversations_js, 'return "DONE";', label="compact done rail label")
    require(conversations_js, 'return "IDLE";', label="compact idle rail label")
    require(conversations_js, "메시지가 접수되어 첫 응답을 기다리는 중입니다.", label="accepted event preview copy")
    require(conversations_js, "작업이 대기열에 올라 있습니다.", label="queued event preview copy")
    require(conversations_js, "최근 작업이 현재 진행 중입니다.", label="running event preview copy")
    require(conversations_js, "제안 단계가 진행 중입니다.", label="proposal event preview copy")
    require(conversations_js, "리뷰 단계가 진행 중입니다.", label="review event preview copy")
    require(conversations_js, "검증 단계가 진행 중입니다.", label="verify event preview copy")
    require(conversations_js, "자동 적용 단계가 진행 중입니다.", label="auto-apply event preview copy")
    require(conversations_js, 'return "HANDOFF";', label="selected live owner handoff marker label")
    require(conversations_js, 'return "NEW";', label="selected live owner new marker label")
    require(conversations_js, 'return "PAUSED";', label="selected live owner paused marker label")
    require(conversations_js, 'return "OWNER";', label="selected live owner session chip label")
    require(jobs_js, "!isAppendStreamConnected(state, state.currentConversationId)", label="polling refetch skip while connected")
    require(render_js, "renderSessionSummary", label="header session summary helper")
    require(render_js, "composerOwnerState", label="composer owner state helper")
    require(render_js, "syncComposerOwnership", label="composer ownership sync helper")
    require(render_js, "compactTargetLabel", label="compact target label helper")
    require(render_js, "summaryHint", label="summary hint helper")
    require(render_js, 'pathLabel = "SWITCHING"', label="summary switching path label")
    require(render_js, 'pathLabel = "HANDOFF"', label="summary handoff path label")
    require(render_js, 'pathLabel = "SSE"', label="summary sse path label")
    require(render_js, 'pathLabel = "DEGRADED"', label="summary degraded path label")
    require(render_js, 'label: "SWITCHING"', label="composer switching label")
    require(render_js, 'label: "HANDOFF"', label="composer handoff label")
    require(render_js, 'label: "READY"', label="composer ready label")
    require(render_js, 'dom.sendRequestButton.dataset.composerBlocked = owner.blocked ? "true" : "false";', label="composer blocked dataset")
    require(render_js, 'dom.sendRequestButton.dataset.composerOwnerState = owner.state;', label="composer owner state dataset")
    require(render_js, 'dom.sendRequestButton.dataset.composerBlockedReason = owner.blockedReason;', label="composer blocked reason dataset")
    require(render_js, 'dom.sessionSummaryScope.textContent = compactTargetLabel(', label="selected-thread summary scope copy")
    require(render_js, 'dom.sessionSummaryRow.dataset.summaryPath = pathLabel.toLowerCase();', label="session summary path dataset")
    require(render_js, 'dom.sessionSummaryRow.dataset.summaryState = stateLabel.toLowerCase();', label="session summary state dataset")
    require(render_js, 'dom.sessionSummaryRow.dataset.followState = sessionIndicator.state;', label="session summary follow-state dataset")
    require(render_js, "selectedThreadLiveSessionIndicator", label="header live-session indicator helper")
    require(render_js, "latestSessionIndicatorEvent", label="header live-session event helper")
    require(render_js, 'dom.sessionSummaryRow.dataset.liveSessionState = sessionIndicator.state;', label="header live-session state dataset")
    require(render_js, 'dom.sessionSummaryRow.dataset.liveSessionSource = sessionIndicator.source;', label="header live-session source dataset")
    require(render_js, 'dom.sessionSummaryRow.dataset.liveSessionReason = sessionIndicator.reason;', label="header live-session reason dataset")
    require(render_js, 'dom.sessionSummaryRow.dataset.liveSessionOwned = sessionIndicator.owned ? "true" : "false";', label="header live-session ownership dataset")
    require(render_js, 'dom.sessionLiveIndicator.hidden = !sessionIndicator.visible;', label="header live-session visibility wiring")
    require(render_js, 'dom.sessionLiveIndicator.dataset.liveSessionTone = sessionIndicator.tone;', label="header live-session tone dataset")
    require(render_js, 'dom.sessionLiveIndicator.dataset.liveSessionSource = sessionIndicator.source;', label="header indicator source dataset")
    require(render_js, 'dom.sessionLiveIndicator.dataset.liveSessionOwned = sessionIndicator.owned ? "true" : "false";', label="header indicator ownership dataset")
    require(render_js, 'dom.sessionLiveIndicator.dataset.liveSessionReason = sessionIndicator.reason;', label="header indicator reason dataset")
    require(render_js, 'label: "SSE OWNER"', label="header live ownership label")
    require(render_js, 'label: "RECONNECT"', label="header live-session reconnect label")
    require(render_js, 'label: "POLLING"', label="header live-session polling label")
    require(render_js, 'reason: followPaused ? "selected-thread-follow-paused" : "selected-thread-following"', label="header live-follow reason")
    require(render_js, 'reason: sessionRotationDetected ? "session-rotation" : retrying ? "retrying" : "polling-fallback"', label="header live-session degraded reason")
    require(render_js, 'type === "codex.exec.retrying"', label="header live-session retry event mapping")
    require(render_js, 'summaryHint("SSE OWNER", "FOLLOW PAUSED")', label="summary paused ownership copy")
    require(render_js, 'summaryHint("SSE OWNER", "LIVE")', label="summary live ownership copy")
    require(render_js, "deriveLiveRunState", label="inline live run state derivation")
    require(render_js, 'state: "sending"', label="local pending sending state")
    require(render_js, 'state: "generating"', label="assistant placeholder generating state")
    require(render_js, 'state: "proposal-phase"', label="proposal phase live run state")
    require(render_js, 'state: "review-phase"', label="review phase live run state")
    require(render_js, 'state: "verify-phase"', label="verify phase live run state")
    require(render_js, 'state: "proposal-ready"', label="proposal ready live run state")
    require(render_js, 'state: "auto-apply"', label="auto-apply live run state")
    require(render_js, 'state: "applied"', label="applied live run state")
    require(render_js, 'phase: "PROPOSAL"', label="proposal phase label")
    require(render_js, 'phase: "REVIEW"', label="review phase label")
    require(render_js, 'phase: "VERIFY"', label="verify phase label")
    require(render_js, 'phase: "READY"', label="proposal ready phase label")
    require(render_js, 'phase: "APPLIED"', label="applied phase label")
    require(render_js, 'goal.proposal.phase.started', label="proposal phase event mapping")
    require(render_js, 'goal.review.phase.started', label="review phase event mapping")
    require(render_js, 'goal.verify.phase.started', label="verify phase event mapping")
    require(render_js, 'goal.proposal.auto_apply.started', label="auto-apply event mapping")
    require(render_js, "renderSessionStrip", label="unified session strip renderer")
    require(render_js, "renderThreadTransition", label="thread transition render helper")
    require(render_js, 'data-thread-transition="loading"', label="thread transition DOM")
    require(render_js, 'dom.conversationTimeline.innerHTML = isThreadTransition', label="thread transition placeholder render branch")
    require(render_js, '? renderThreadTransition(currentState)', label="thread transition placeholder render path")
    require(render_js, ": '<p class=\"timeline-empty\">새 대화를 만들면 요청과 이벤트가 여기 쌓입니다.</p>';",
            label="empty state limited to non-transition path")
    require(render_js, 'conversationState: isThreadTransition ? "새 대화 스냅샷을 연결하는 중입니다." : "아직 대화 세션이 없습니다.",', label="thread transition conversation state copy")
    require(render_js, 'threadTitle: isThreadTransition ? String(threadTransition.targetTitle || "대화 전환 중") : "새 대화를 시작하세요",', label="thread transition title copy")
    require(render_js, 'dom.threadScroller.dataset.threadTransitionState = isThreadTransition ? "loading" : "idle";', label="thread transition state dataset")
    require(render_js, 'dom.threadScroller.dataset.threadTransitionConversationId = isThreadTransition', label="thread transition conversation dataset")
    require(render_js, 'renderSessionStrip(dom, currentState, null);', label="thread transition composer shell render path")
    require(render_js, 'syncComposerOwnership(dom, currentState, null);', label="thread transition composer owner switching path")
    require(render_js, 'conversationId: isThreadTransition ? String(threadTransition.targetConversationId || "") : "",', label="thread transition live-follow target reset")
    require(render_js, 'presentation === "sending"', label="sending presentation state")
    require(render_js, 'data-pending-local="true"', label="pending local timeline marker")
    require(render_js, 'data-pending-assistant="true"', label="pending assistant timeline marker")
    require(render_js, "local-pending", label="pending local render source")
    require(render_js, "local-assistant-placeholder", label="assistant placeholder render source")
    require(render_js, "pendingHandoffState", label="single pending handoff render helper")
    require(render_js, 'stage: "pending-user"', label="pending user handoff stage")
    require(render_js, 'stage: "pending-assistant"', label="pending assistant handoff stage")
    require(render_js, "selectedThreadSseOwned", label="pending assistant selected-thread SSE ownership guard")
    require(render_js, "pendingOutgoing.status === \"awaiting-assistant\" &&", label="awaiting-assistant ownership render guard")
    require(render_js, 'const handoffVisible = handoffState.stage === "pending-assistant" && selectedThreadSseOwned;', label="inline handoff visibility guard")
    require(render_js, "const liveVisible =", label="inline live visibility guard")
    require(render_js, 'renderSource === "sse"', label="inline live render-source guard")
    require(render_js, 'status === "live"', label="inline live healthy-status guard")
    require(render_js, "pendingUserCount", label="pending user count dataset state")
    require(render_js, "pendingAssistantCount", label="pending assistant count dataset state")
    require(render_js, "handoffState.items", label="single pending handoff item render wiring")
    require(render_js, 'dom.threadScroller.dataset.pendingHandoffStage = handoffState.stage', label="pending handoff stage dataset")
    require(render_js, 'dom.threadScroller.dataset.pendingUserCount = String(handoffState.pendingUserCount)', label="pending user count dataset")
    require(render_js, 'dom.threadScroller.dataset.pendingAssistantCount = String(handoffState.pendingAssistantCount)', label="pending assistant count dataset")
    require(conversations_js, "syncSelectedAppSession", label="selected app session sync helper")
    require(conversations_js, 'option.dataset.sessionId = app.session_id || "";', label="selected app session id option dataset")
    require(conversations_js, "rotationDetected", label="selected app session rotation detection")
    require(jobs_js, "renderJobActivity(dom, state.conversationCache, state.currentJobId, payload, state);", label="job panel receives current state for SSE ownership")
    require(render_js, "autonomyDetailMeta", label="secondary panel autonomy detail meta wiring")
    require(store_js, "autonomySummary: null,", label="autonomy summary state cache")
    require(app_js, "buildAutonomySummary", label="autonomy summary helper import")
    require(conversations_js, "buildAutonomySummary", label="autonomy summary helper dependency")
    require(conversations_js, "state.autonomySummary = buildAutonomySummary(goal);", label="autonomy summary state hydration")
    require(conversations_js, "state.autonomySummary = null;", label="autonomy summary clear state")
    require(render_js, "dataset.sessionPresentation", label="session strip presentation dataset")
    require(render_js, "dataset.sessionTerminal", label="session strip terminal dataset")
    require(render_js, "sessionRail", label="session rail local expansion state")
    require(render_js, "transportChip", label="composer state transport chip helper")
    require(render_js, "phaseChip", label="composer state phase chip helper")
    require(render_js, "proposalChip", label="composer state proposal chip helper")
    require(render_js, "phaseDetailHint", label="phase detail hint helper")
    require(render_js, "shouldShowComposerLiveStrip", label="composer live strip visibility helper")
    require(render_js, "selectedThreadInlineSessionState", label="inline session visibility helper")
    require(render_js, "if (inlineState.visible) {", label="composer strip suppression guard")
    require(render_js, "renderInlineSessionBlock", label="inline session workspace block helper")
    require(render_js, "summarizeInlineAutonomy", label="inline autonomy summary helper")
    require(render_js, "buildAutonomySummary", label="shared autonomy summary builder")
    require(render_js, 'data-live-autonomy="true"', label="inline autonomy DOM")
    require(render_js, 'data-autonomy-path-verdict="', label="inline autonomy path verdict dataset")
    require(render_js, 'data-autonomy-verifier-acceptability="', label="inline autonomy verifier dataset")
    require(render_js, 'data-autonomy-blocker-reason="', label="inline autonomy blocker dataset")
    require(render_js, 'data-autonomy-iteration="', label="inline autonomy iteration dataset")
    require(render_js, '<span>Iteration</span>', label="inline autonomy iteration copy")
    require(render_js, '<span>Path</span>', label="inline autonomy path copy")
    require(render_js, '<span>Signals</span>', label="inline autonomy signals copy")
    require(render_js, "INLINE_TERMINAL_RETENTION_MS = 12000", label="inline terminal retention window")
    require(render_js, "shouldRetainInlineTerminalPhase", label="inline terminal retention helper")
    require(render_js, 'data-selected-thread-live-block="true"', label="inline session workspace block DOM")
    require(render_js, 'data-live-block-owner="selected-thread"', label="inline session workspace block owner DOM")
    require(render_js, 'data-live-owned="true"', label="inline session workspace block ownership DOM")
    require(render_js, 'data-live-block-phase="', label="inline session workspace block phase DOM")
    require(render_js, 'data-live-block-terminal="', label="inline session workspace block terminal DOM")
    require(render_js, 'const retainedTerminalVisible = shouldRetainInlineTerminalPhase(', label="inline terminal retention wiring")
    require(render_js, '(!liveRun.terminal || retainedTerminalVisible);', label="inline terminal visibility guard")
    require(render_js, 'liveRun.terminal ? "terminal" : String(liveRun.state || "live")', label="inline terminal stage mapping")
    require(render_js, 'Date.now() - createdAtMs <= INLINE_TERMINAL_RETENTION_MS;', label="inline terminal retention deadline")
    require(render_js, "(liveRun.phase !== \"READY\" && liveRun.phase !== \"APPLIED\")", label="inline terminal phase scope")
    require(render_js, "latestAppendId > terminalAppendId", label="inline terminal next-append clear guard")
    require(render_js, "renderTranscriptLiveActivity", label="transcript live activity helper")
    require(render_js, "transcriptLiveTone", label="transcript live activity tone helper")
    require(render_js, "composerActionHint", label="composer affordance hint helper")
    require(render_js, "threadMetaSummary", label="thread meta phase summary helper")
    require(render_js, "sessionProvenance", label="session provenance helper")
    require(render_js, "toggleSessionRail", label="session rail toggle helper")
    require(render_js, "dataset.sessionCollapsed", label="session strip collapsed dataset")
    require(render_js, "showComposerLiveStrip", label="composer live strip visibility guard")
    require(render_js, 'transport === "sse"', label="composer live strip SSE transport guard")
    require(render_js, 'status !== "live"', label="composer live strip healthy-only transport guard")
    require(render_js, 'return inlineState.renderSource === "sse";', label="composer live strip healthy render-source guard")
    require_absent(render_js, 'status === "reconnecting" || status === "connecting" || status === "offline"', label="legacy degraded strip visibility guard")
    require(render_js, 'dom.sessionStrip.hidden = !showComposerLiveStrip', label="composer live strip hidden when inactive")
    require(render_js, "const sessionOwnerState = selectedThreadLiveSessionIndicator(currentState, conversation, liveRun);", label="composer live strip ownership helper wiring")
    require(render_js, 'const liveOwned = inlineState.selectedThreadSseOwned && inlineState.status === "live" && inlineState.renderSource === "sse";', label="composer live strip live ownership guard")
    require(render_js, 'dom.sessionStrip.dataset.liveOwned = liveOwned ? "true" : "false"', label="composer live strip ownership dataset")
    require(render_js, 'dom.sessionStrip.dataset.sessionOwner = liveOwned ? "selected-thread" : "none";', label="composer live strip selected-thread owner dataset")
    require(render_js, 'dom.sessionStrip.dataset.followState = sessionOwnerState.state;', label="composer live strip follow-state dataset")
    require(render_js, 'dom.threadScroller.dataset.sessionOwner = liveOwned ? "selected-thread" : "none";', label="thread scroller selected-thread owner dataset")
    require(render_js, 'proposalState.label !== "NONE"', label="composer live strip proposal chip compaction")
    require(render_js, 'sessionOwnerState.state === "paused" ? "follow paused" : "following"', label="composer live strip follow meta")
    require(render_js, "composerActionHint(status, presentation, liveRun)", label="composer live strip compact action detail")
    require(render_js, "session-chip", label="session chip render markup")
    require(render_js, "export function renderJobActivity(dom, conversation, currentJobId, jobPayload = null, currentState = null)", label="job activity current-state signature")
    require(render_js, "const selectedThreadSseOwned =", label="job activity selected-thread SSE ownership guard")
    require(render_js, "const liveRun = currentState ? deriveLiveRunState(conversation, currentState)", label="job activity live-run ownership source")
    require(render_js, "const eventJobId = String(liveRun.jobId || currentJobId || conversation?.latest_job_id || \"\")", label="job activity event job id")
    require(render_js, "const phase = selectedThreadSseOwned", label="job activity phase ownership switch")
    require(render_js, 'String(liveRun.phase || "IDLE").toUpperCase()', label="job activity SSE phase label")
    require(render_js, 'phaseLabel(jobPayload?.status || latestEvent?.status || "", latestEvent?.type || "")', label="job activity polling fallback phase label")
    require(render_js, "currentState.latestProposalJobId =", label="apply readiness from selected-thread live state")
    require(render_js, 'liveRun.state === "proposal-ready"', label="proposal-ready apply enable guard")
    require(render_js, "updateProposalButton(dom, currentState.latestProposalJobId);", label="apply button updated from selected-thread live state")
    require(render_js, 'renderJobActivity(dom, conversation, currentState.currentJobId || conversation.latest_job_id || "", null, currentState);', label="selected conversation job activity uses current state")
    require(render_js, "headerPhaseTone", label="thread header phase tone helper")
    require(render_js, "threadTitle", label="thread title header wiring")
    require(render_js, "threadPhaseChip", label="thread phase chip wiring")
    require(render_js, 'return { label: "SEND", tone: "thinking" };', label="compact send transport chip")
    require(render_js, 'return { label: "ACCEPTED", tone: "neutral" };', label="compact accepted handoff chip")
    require(render_js, 'return { label: "RECONNECT", tone: "warning" };', label="compact reconnect transport chip")
    require(render_js, 'return { label: "OPEN", tone: "neutral" };', label="compact connecting transport chip")
    require(render_js, 'return { label: "OFFLINE", tone: "danger" };', label="compact offline transport chip")
    require(render_js, 'return { label: "READY", tone: "healthy" };', label="compact ready chip")
    require(render_js, 'return { label: "APPLIED", tone: "healthy" };', label="compact applied chip")
    require(render_js, 'return { label: "BLOCKED", tone: "warning" };', label="compact blocked proposal chip")
    require(render_js, 'return "복구 중";', label="compact reconnect action hint")
    require(render_js, 'return "복구 필요";', label="compact offline action hint")
    require(render_js, 'return "연결 중";', label="compact connecting action hint")
    require(render_js, 'return "전송 중";', label="compact sending action hint")
    require(render_js, 'return "handoff 완료";', label="compact accepted action hint")
    require(render_js, 'return "HYPOTHESIS";', label="phase detail proposal hint")
    require(render_js, 'return "REVIEW SIGNAL";', label="phase detail review hint")
    require(render_js, 'return "VERIFY SIGNAL";', label="phase detail verify hint")
    require(render_js, 'return "AUTO APPLY";', label="phase detail auto-apply hint")
    require(render_js, 'return "READY TO APPLY";', label="phase detail proposal-ready hint")
    require(render_js, 'return "APPLY COMPLETE";', label="phase detail applied hint")
    require(render_js, 'return "응답 생성";', label="compact generating action hint")
    require(render_js, 'return "실행 중";', label="compact live execution action hint")
    require(render_js, 'return "계속 입력";', label="compact live action hint")
    require(render_js, 'return "입력 가능";', label="compact idle action hint")
    require(render_js, '"RECONNECT"', label="degraded stream provenance label")
    require(render_js, '"OPEN"', label="connecting stream provenance label")
    require(render_js, '"OFFLINE"', label="offline stream provenance label")
    require(render_js, 'dom.sessionStripToggle.hidden = true', label="session strip toggle hidden")
    require(render_js, 'dom.sendRequestButton.textContent = status === "live" || presentation === "sending" ? "추가 지시 보내기" : "메시지 보내기"', label="contextual send copy")
    require(render_js, 'dom.applyProposalButton.textContent = liveRun.state === "proposal-ready" ? "지금 제안 적용" : "제안 적용"', label="contextual apply copy")
    require(render_js, "dataset.liveRunState", label="live run state dataset")
    require(render_js, "dataset.liveRunPhase", label="live run phase dataset")
    require(render_js, "dataset.liveRunSource", label="live run source dataset")
    require(render_js, "dataset.followState", label="follow-state dataset")
    require(render_js, 'data-live-activity-turn="true"', label="transcript live activity DOM")
    require(render_js, 'data-append-source="sse-live-activity"', label="transcript live activity provenance DOM")
    require(render_js, "selected thread", label="transcript live activity selected-thread copy")
    require(render_js, 'transport !== "sse" || renderSource !== "sse"', label="transcript live activity SSE-only guard")
    require(render_js, "syncJumpToLatest", label="jump-to-latest sync helper")
    require(render_js, "updateLiveFollowFromScroll", label="live follow scroll helper")
    require(render_js, "jumpToLatest", label="jump-to-latest action helper")
    require(render_js, "currentState.liveFollow", label="live follow state wiring")
    require(render_js, "lastSeenAppendId", label="live follow seen append cursor")
    require(render_js, "pendingAppendCount", label="live follow unseen append count")
    require(render_js, "followRenderSource", label="jump-to-latest render source dataset")
    require(render_js, 'const liveOwned =', label="follow control live-owned guard")
    require(render_js, 'const terminalIdle = String(dom.threadScroller?.dataset.sessionTerminal || "false") === "true";', label="follow control terminal-idle guard")
    require(render_js, 'const detached = !Boolean(liveFollow.isFollowing);', label="follow control detached-state guard")
    require(render_js, 'const hasBacklog = unseenCount > 0;', label="follow control backlog guard")
    require(render_js, 'const pausedVisible = liveOwned && detached && !hasBacklog;', label="follow control paused visibility guard")
    require(render_js, 'const followState = hasBacklog ? "new" : "paused";', label="follow control state mapping")
    require(render_js, 'const isVisible = Boolean(liveOwned && detached);', label="follow control visibility mapping")
    require(render_js, 'dom.jumpToLatestButton.dataset.followOwned = liveOwned ? "selected-thread" : "none";', label="follow control owner dataset")
    require(render_js, 'dom.jumpToLatestButton.dataset.followState = isVisible ? followState : "hidden";', label="follow control state dataset")
    require(render_js, 'dom.jumpToLatestButton.dataset.followCount = String(isVisible ? unseenCount : 0);', label="follow control unseen count dataset")
    require(render_js, 'stateLabel = followState === "new" ? "NEW" : "PAUSED";', label="follow control explicit state labels")
    require(render_js, 'detailLabel =', label="follow control detail label")
    require(render_js, "새 live append", label="follow control new copy")
    require(render_js, "live follow paused", label="follow control paused copy")
    require(render_js, "data-append-source", label="append provenance attribute")
    require(render_js, "dataset.streamState = status", label="stream-state dataset")
    require(render_js, "dataset.renderSource = lastRenderSource", label="render-source dataset")
    require(conversations_js, 'dom.threadScroller.dataset.pendingConversationId = conversationId', label="thread switch pending marker")
    require(conversations_js, "state.currentConversationId && state.currentConversationId !== conversationId", label="thread switch clear guard")
    require(store_js, "threadTransition", label="thread transition state")
    require(store_js, "appendStream", label="append stream state")
    require(store_js, "pendingOutgoing", label="pending outgoing state")
    require(store_js, "assistantCreatedAt", label="assistant placeholder pending timestamp state")
    require(store_js, "baselineAppendId", label="pending handoff baseline append id state")
    require(store_js, "isAppendStreamConnected", label="append stream connection helper")
    require(store_js, "liveFollow", label="live follow state")
    require(store_js, "lastSeenAppendId", label="live follow seen append state")
    require(store_js, "pendingAppendCount", label="live follow unseen append state")
    require(index_html, 'id="session-strip"', label="session strip DOM")
    require(index_html, 'id="session-strip-state"', label="session strip state DOM")
    require(index_html, 'id="session-strip-meta"', label="session strip meta DOM")
    require(index_html, 'id="session-strip-detail"', label="session strip detail DOM")
    require(index_html, 'id="composer-owner-row"', label="composer owner row DOM")
    require(index_html, 'id="composer-owner-state"', label="composer owner state DOM")
    require(index_html, 'id="composer-owner-target"', label="composer owner target DOM")
    require(index_html, 'id="composer-owner-copy"', label="composer owner copy DOM")
    require(index_html, 'data-thread-header="conversation"', label="conversation-first thread header DOM")
    require(index_html, 'id="thread-title"', label="thread title DOM")
    require(index_html, 'id="thread-phase-chip"', label="thread phase chip DOM")
    require(index_html, 'id="session-summary-row"', label="session summary row DOM")
    require(index_html, 'id="recent-thread-rail"', label="recent-thread rail DOM")
    require(index_html, 'id="recent-thread-rail-list"', label="recent-thread rail list DOM")
    require(index_html, 'id="session-live-indicator"', label="header live-session indicator DOM")
    require(index_html, 'data-live-session-source="none"', label="header live-session source default")
    require(index_html, 'data-live-session-owned="false"', label="header live-session ownership default")
    require(index_html, 'data-live-session-reason="idle"', label="header live-session reason default")
    require(index_html, 'id="session-summary-scope"', label="session summary scope DOM")
    require(index_html, 'id="session-summary-path"', label="session summary path DOM")
    require(index_html, 'id="session-summary-state"', label="session summary state DOM")
    require(index_html, 'id="session-summary-copy"', label="session summary copy DOM")
    require(index_html, 'id="session-strip-toggle"', label="session strip toggle DOM")
    require(index_html, 'data-activity-bar="composer-adjacent"', label="composer-adjacent activity bar DOM")
    require(index_html, 'class="composer-toolbar"', label="chat-style composer toolbar DOM")
    require(index_html, 'class="composer-send-primary"', label="primary send button DOM")
    require(index_html, "composer-secondary-action", label="secondary composer action DOM")
    require(index_html, 'id="composer-utility-menu"', label="composer utility menu DOM")
    require(index_html, 'id="composer-utility-toggle"', label="composer utility toggle DOM")
    require(index_html, 'id="composer-utility-cluster"', label="composer utility cluster DOM")
    require(index_html, 'data-composer-layout="chat-first"', label="chat-first composer footer DOM")
    require(index_html, 'data-composer-utility-panel="compact"', label="compact composer utility panel DOM")
    require(index_html, 'class="toggle inline composer-utility-toggle"', label="composer utility toggle DOM")
    require(index_html, 'id="conversation-footer-dock"', label="conversation footer dock DOM")
    require(index_html, 'id="active-session-row"', label="active session row DOM")
    require(index_html, 'id="active-session-owner"', label="active session owner DOM")
    require(index_html, 'id="active-session-state"', label="active session state DOM")
    require(index_html, 'id="active-session-follow"', label="active session follow DOM")
    require(index_html, 'id="active-session-title"', label="active session title DOM")
    require(index_html, 'id="active-session-meta"', label="active session meta DOM")
    require(index_html, 'data-active-session-owned="false"', label="active session owned default")
    require(index_html, 'data-active-session-source="none"', label="active session source default")
    require(index_html, 'data-active-session-phase="IDLE"', label="active session phase default")
    require(index_html, 'data-active-session-unseen-count="0"', label="active session unseen default")
    require(index_html, 'data-footer-dock="session-composer"', label="footer dock mode DOM")
    require(index_html, 'data-session-workspace="conversation-first"', label="conversation-first session workspace DOM")
    require(index_html, 'id="jump-to-latest"', label="jump-to-latest DOM")
    require(index_html, 'class="jump-to-latest-chip"', label="jump-to-latest chip DOM")
    require(index_html, 'class="jump-to-latest-copy"', label="jump-to-latest copy DOM")
    require(index_html, 'id="autonomy-detail"', label="secondary panel autonomy detail DOM")
    require(index_html, 'id="autonomy-detail-meta"', label="secondary panel autonomy detail meta DOM")
    require(index_html, 'id="secondary-panel"', label="secondary panel DOM")
    require(index_html, 'data-secondary-panel-mode="compact-sidecar"', label="compact side panel DOM")
    require(index_html, 'id="secondary-panel-toggle"', label="secondary panel toggle DOM")
    require(index_html, 'id="secondary-panel-close"', label="secondary panel close DOM")
    require(index_html, 'id="nav-sheet-toggle"', label="mobile nav toggle DOM")
    require(index_html, 'id="nav-sheet-close"', label="mobile nav close DOM")
    require(index_html, 'id="nav-sheet-scrim"', label="mobile nav scrim DOM")
    require(index_html, 'id="nav-sheet"', label="mobile nav sheet DOM")
    require(index_html, 'data-mobile-surface="sheet"', label="mobile nav sheet surface marker")
    require(index_html, 'data-mobile-nav-priority="conversations"', label="mobile nav conversation priority DOM")
    require(index_html, 'data-nav-primary="threads"', label="mobile nav threads-first section DOM")
    require(index_html, 'data-nav-secondary="ops"', label="mobile nav secondary operator section DOM")
    require(index_html, 'id="selected-app-summary"', label="selected app summary DOM")
    require(index_html, 'data-sidebar-app-summary="compact"', label="compact app summary DOM")
    require(index_html, 'data-primary-surface="conversation"', label="active conversation primary surface DOM")
    require(index_html, 'aria-controls="nav-sheet"', label="mobile nav toggle controls DOM")
    require(index_html, 'aria-expanded="false"', label="mobile nav closed default DOM")
    require(index_html, 'id="nav-ops-section"', label="mobile operator section DOM")
    require(index_html, 'id="nav-ops-summary"', label="mobile operator summary DOM")
    require(index_html, 'id="thread-scroller" class="thread-scroller" tabindex="-1"', label="conversation surface focus target DOM")
    require(app_js, "internalConversationAppendStreamUrl", label="controller dependency wiring")
    require(app_js, "showPendingOutgoing", label="pending outgoing submit wiring")
    require(app_js, "showPendingAssistant", label="pending assistant submit wiring")
    require(app_js, "clearPendingOutgoing", label="pending outgoing clear wiring")
    require(app_js, "setNavigationOpen", label="mobile nav state helper")
    require(app_js, "isPhoneViewport", label="phone breakpoint helper")
    require(app_js, "focusPrimaryNavAction", label="mobile nav primary action focus helper")
    require(app_js, "returnFocusToConversationSurface", label="mobile nav conversation return focus helper")
    require(app_js, "syncMobileWorkspaceMode", label="mobile nav mode helper")
    require(app_js, 'dom.secondaryPanelToggle.setAttribute("aria-expanded", isOpen ? "true" : "false");', label="secondary panel aria expanded sync")
    require(app_js, 'document.body.dataset.mobileNavMode = isPhoneViewport() ? "drawer" : "desktop"', label="mobile nav mode dataset")
    require(app_js, 'document.body.dataset.mobileWorkspace = isOpen ? "navigation" : "conversation"', label="mobile workspace state helper")
    require(app_js, 'dom.navOpsSection.open = false;', label="mobile operator section collapse on phone")
    require(app_js, 'dom.navSheetToggle.setAttribute("aria-expanded", isOpen ? "true" : "false")', label="mobile nav toggle expanded state")
    require(app_js, 'navSheet.setAttribute("aria-hidden", isOpen ? "false" : "true")', label="mobile nav sheet aria state")
    require(app_js, "syncNavOpsSection", label="mobile operator section state helper")
    require(app_js, "dom.navOpsSection.open = false;", label="operator section collapsed by default")
    require(app_js, 'primaryAction.focus({ preventScroll: true })', label="mobile nav focuses first thread action")
    require(app_js, 'preferredTarget.focus({ preventScroll: true })', label="mobile conversation surface focus return")
    require(app_js, "updateLiveFollowFromScroll", label="live follow scroll event wiring")
    require(app_js, "jumpToLatest", label="jump-to-latest button wiring")
    require(app_js, "reengageLiveFollowFromComposer", label="composer reengages live follow helper")
    require(app_js, 'dom.requestTextInput.addEventListener("focus", reengageLiveFollowFromComposer)', label="composer focus reengages live follow")
    require(app_js, 'dom.requestTextInput.addEventListener("input", reengageLiveFollowFromComposer)', label="composer input reengages live follow")
    require(app_js, "toggleSessionRail", label="session rail toggle wiring")
    require(app_js, 'dom.recentThreadRailList?.addEventListener("click", async (event) => {', label="recent-thread rail click wiring")
    require(app_js, "setSecondaryPanelOpen", label="secondary panel state helper")
    require(app_js, "setComposerUtilityOpen", label="composer utility state helper")
    require(app_js, "syncSendButtonState", label="composer send availability helper")
    require(app_js, 'dom.sendRequestButton.dataset.sendBusy = "true";', label="composer send busy start")
    require(app_js, 'dom.sendRequestButton.dataset.sendBusy = "false";', label="composer send busy end")
    require(app_js, 'dom.sendRequestButton?.dataset.composerBlocked === "true"', label="composer blocked guard")
    require(app_js, 'dom.composerUtilityMenu.dataset.composerUtilityOpen = isOpen ? "true" : "false";', label="composer utility dataset state")
    require(app_js, 'dom.composerUtilityCluster.hidden = !isOpen;', label="composer utility hidden state")
    require(app_js, 'dom.composerUtilityToggle.setAttribute("aria-expanded", isOpen ? "true" : "false");', label="composer utility aria state")
    require(app_js, 'window.innerWidth > 860', label="mobile nav resize reset")
    require(deployed_console_sh, 'WORKSPACE_APP_ID="${WORKSPACE_APP_ID:-factory-runtime}"', label="workspace gate app default")
    require(deployed_console_sh, 'python3 ./scripts/verify_deployed_workspace_gate.py', label="deployed workspace gate wiring")
    require(api_js, 'sessionId: option.dataset.sessionId || ""', label="selected app session id API wiring")
    require(store_js, "appSession", label="selected app session state")
    require(deployed_workspace_py, 'DEFAULT_REQUEST_TEXT = (', label="workspace gate default request")
    require(deployed_workspace_py, 'goal.proposal.phase.started', label="workspace gate proposal phase assertion")
    require(deployed_workspace_py, 'goal.review.phase.started', label="workspace gate review phase assertion")
    require(deployed_workspace_py, 'goal.verify.phase.started', label="workspace gate verify phase assertion")
    require(deployed_workspace_py, "proposal.ready", label="workspace gate proposal ready assertion")
    require(deployed_workspace_py, 'conversation.append', label="workspace gate sse append assertion")
    require(deployed_workspace_py, "phaseChip", label="workspace gate browser-visible phase chip assertion")
    require(deployed_workspace_py, "dataset.liveRunPhase", label="workspace gate live phase dataset assertion")
    require(deployed_workspace_py, "dataset.streamState", label="workspace gate transport dataset assertion")
    require(deployed_workspace_py, 'id="session-live-indicator"', label="workspace gate header live-session DOM assertion")
    require(deployed_workspace_py, "selectedThreadLiveSessionIndicator", label="workspace gate header live-session helper assertion")
    require(deployed_workspace_py, "dataset.liveSessionState", label="workspace gate header live-session dataset assertion")
    require(deployed_workspace_py, 'codex.exec.retrying', label="workspace gate retry degradation assertion")
    require(deployed_workspace_py, "unexpected session rotation", label="workspace gate session rotation guard")
    require(styles_css, 'body[data-nav-open="true"] .sidebar', label="mobile nav drawer CSS")
    require(styles_css, 'body[data-mobile-nav-mode="drawer"] .sidebar[data-mobile-nav-priority="conversations"] .sidebar-primary-nav', label="mobile nav drawer mode CSS")
    require(styles_css, 'body[data-mobile-workspace="conversation"] .main-stage', label="conversation-first mobile surface CSS")
    require(styles_css, "touch-action: none;", label="mobile nav open touch lock CSS")
    require(styles_css, 'body[data-secondary-panel-open="true"] .desktop-shell', label="desktop secondary panel layout CSS")
    require(styles_css, "grid-template-columns: 15rem minmax(0, 1fr);", label="desktop two-pane shell width")
    require(styles_css, "grid-template-columns: 13.5rem minmax(0, 1fr);", label="desktop two-pane shell width at medium desktop")
    require(styles_css, ".autonomy-detail-card", label="secondary panel autonomy detail card CSS")
    require(styles_css, ".secondary-panel", label="secondary panel CSS")
    require(styles_css, "position: fixed;", label="desktop secondary panel overlay positioning")
    require(styles_css, "width: min(18.5rem, calc(100vw - 2rem));", label="desktop secondary panel overlay width")
    require(styles_css, ".thread-title-row", label="thread title row CSS")
    require(styles_css, ".session-summary-row", label="session summary row CSS")
    require(styles_css, ".recent-thread-rail", label="recent-thread rail CSS")
    require(styles_css, ".recent-thread-rail-list", label="recent-thread rail list CSS")
    require(styles_css, ".recent-thread-chip", label="recent-thread chip CSS")
    require(styles_css, '.recent-thread-chip[data-thread-state="switching"] .recent-thread-token[data-recent-thread-state]', label="recent-thread switching chip CSS")
    require(styles_css, '.recent-thread-chip[data-live-owner="true"] .recent-thread-token[data-recent-thread-owner]', label="recent-thread owner chip CSS")
    require(styles_css, '.recent-thread-chip[data-live-owner-state="new"] .recent-thread-token[data-recent-thread-follow]', label="recent-thread new follow chip CSS")
    require(styles_css, ".session-live-indicator", label="header live-session indicator CSS")
    require(styles_css, '.session-live-indicator[data-live-session-tone="healthy"]', label="header live-session healthy CSS")
    require(styles_css, '.session-live-indicator[data-live-session-tone="warning"]', label="header live-session warning CSS")
    require(styles_css, '.session-live-indicator[data-live-session-tone="danger"]', label="header live-session danger CSS")
    require(styles_css, ".session-summary-chip", label="session summary chip CSS")
    require(styles_css, ".session-summary-copy", label="session summary copy CSS")
    require(styles_css, '.session-summary-row[data-summary-path="switching"] .session-summary-chip[data-summary-chip="path"]', label="summary switching chip CSS")
    require(styles_css, '.session-summary-row[data-summary-path="handoff"] .session-summary-chip[data-summary-chip="path"]', label="summary handoff chip CSS")
    require(styles_css, '.session-summary-row[data-summary-path="sse"] .session-summary-chip[data-summary-chip="path"]', label="summary sse chip CSS")
    require(styles_css, ".thread-phase-chip", label="thread phase chip CSS")
    require(styles_css, ".thread-sidecar", label="thread sidecar CSS")
    require(styles_css, "width: min(100%, 54rem);", label="dominant conversation column width")
    require(styles_css, ".conversation-card-live", label="conversation card live badge CSS")
    require(styles_css, ".conversation-card-marker", label="conversation card selected badge CSS")
    require(styles_css, ".conversation-card-session", label="conversation card session badge CSS")
    require(styles_css, '.conversation-card[data-live-owner="true"]', label="selected live owner card CSS")
    require(styles_css, ".conversation-card-live-owner-row", label="selected live owner row CSS")
    require(styles_css, ".conversation-card-live-detail", label="selected live detail CSS")
    require(styles_css, ".conversation-card-live-follow", label="selected live follow CSS")
    require(styles_css, ".conversation-card-tags", label="conversation card session tag row CSS")
    require(styles_css, ".conversation-card-preview", label="conversation card preview CSS")
    require(styles_css, ".active-session-row", label="active session row CSS")
    require(styles_css, ".active-session-chip", label="active session chip CSS")
    require(styles_css, ".active-session-title", label="active session title CSS")
    require(styles_css, ".active-session-meta", label="active session meta CSS")
    require(styles_css, '.active-session-row[data-active-session-state="switching"] .active-session-chip[data-active-chip="state"]', label="active session switching chip CSS")
    require(styles_css, '.active-session-row[data-active-session-follow="new"] .active-session-chip[data-active-chip="follow"]', label="active session new follow chip CSS")
    require(styles_css, '.conversation-card-preview[data-preview-lines="1"]', label="single-line conversation preview CSS")
    require(styles_css, '.conversation-card[data-thread-state="active"] .conversation-card-live', label="active card state CSS")
    require(styles_css, '.conversation-card[data-thread-state="active"] .conversation-card-session', label="active session marker CSS")
    require(styles_css, '.conversation-card[data-thread-state="review"] .conversation-card-live', label="review card state CSS")
    require(styles_css, '.conversation-card[data-thread-state="verify"] .conversation-card-live', label="verify card state CSS")
    require(styles_css, '.conversation-card[data-thread-state="ready"] .conversation-card-live', label="ready card state CSS")
    require(styles_css, '.conversation-card[data-live-owner="true"] .conversation-card-marker', label="selected live owner marker CSS")
    require(styles_css, '.conversation-card[data-live-owner="true"] .conversation-card-session', label="selected live owner session CSS")
    require(styles_css, '.conversation-card[data-live-owner-state="handoff"] .conversation-card-marker', label="selected handoff owner marker CSS")
    require(styles_css, '.conversation-card[data-live-owner-state="new"] .conversation-card-marker', label="selected new owner marker CSS")
    require(styles_css, '.conversation-card[data-live-owner-state="paused"] .conversation-card-marker', label="selected paused owner marker CSS")
    require(styles_css, '.conversation-card-live-owner-row[data-live-owner-state="handoff"] .conversation-card-live-follow', label="selected handoff follow chip CSS")
    require(styles_css, '.conversation-card-live-owner-row[data-live-owner-state="new"] .conversation-card-live-follow', label="selected new follow chip CSS")
    require(styles_css, '.conversation-card-live-owner-row[data-live-owner-state="paused"] .conversation-card-live-follow', label="selected paused follow chip CSS")
    require_absent(conversations_js, "메시지 handoff 중", label="legacy selected row handoff prose")
    require_absent(conversations_js, "첫 응답 대기", label="legacy selected row accepted prose")
    require_absent(conversations_js, "선택된 세션 연결 중", label="legacy selected row connecting prose")
    require_absent(conversations_js, "선택된 세션 복구 중", label="legacy selected row reconnect prose")
    require(styles_css, '.conversation-card[data-thread-state="failed"] .conversation-card-live', label="failed card state CSS")
    require(styles_css, '.conversation-card[data-thread-state="idle"] .conversation-card-live', label="idle card state CSS")
    require(styles_css, ".timeline-item.message.user.pending-local", label="pending local message CSS")
    require(styles_css, ".timeline-item.message.assistant.pending-assistant", label="pending assistant message CSS")
    require(styles_css, ".timeline-item.live-activity", label="transcript live activity CSS")
    require(styles_css, ".session-inline-block", label="inline session block CSS")
    require(styles_css, ".session-inline-chip", label="inline session chip CSS")
    require(styles_css, ".session-inline-meta", label="inline session meta CSS")
    require(styles_css, ".timeline-live-row", label="transcript live activity chip row CSS")
    require(styles_css, ".timeline-live-chip", label="transcript live activity chip CSS")
    require(styles_css, ".session-strip", label="session strip CSS")
    require(styles_css, ".composer-owner-row", label="composer owner row CSS")
    require(styles_css, ".composer-owner-chip", label="composer owner chip CSS")
    require(styles_css, ".composer-owner-target", label="composer owner target CSS")
    require(styles_css, '.composer-send-primary[data-composer-blocked="true"]', label="composer blocked send CSS")
    require(styles_css, '.session-strip[data-live-owned="true"]', label="composer live strip active CSS")
    require(styles_css, '.session-strip[data-stream-state="reconnecting"]', label="composer reconnecting strip CSS")
    require(styles_css, '.session-strip[data-stream-state="offline"]', label="composer offline strip CSS")
    require(styles_css, '.session-strip[data-stream-state="connecting"]', label="composer connecting strip CSS")
    require(styles_css, ".session-activity-bar", label="composer activity bar CSS")
    require(styles_css, ".session-chip", label="composer state chip CSS")
    require(styles_css, "flex-wrap: wrap;", label="composer activity inline wrap CSS")
    require(styles_css, "justify-content: flex-start;", label="composer activity inline alignment CSS")
    require(styles_css, ".session-strip-toggle {\n  min-width: 5.8rem;\n  margin-left: auto;", label="composer activity toggle push CSS")
    require(styles_css, ".session-strip-meta,\n.session-strip-detail {\n  color: var(--muted);", label="composer activity inline metadata CSS")
    require(styles_css, "display: inline-flex;", label="composer activity inline chip display CSS")
    require_absent(styles_css, ".session-strip-main", label="legacy composer activity main CSS")
    require_absent(styles_css, ".session-strip-side", label="legacy composer activity side CSS")
    require(render_js, 'const stage = handoffVisible ? "handoff" : liveRun.terminal ? "terminal" : String(liveRun.state || "live");', label="inline block handoff stage mapping")
    require(render_js, 'const phaseLabel = handoffVisible ? "HANDOFF" : String(liveRun.phase || "LIVE").toUpperCase();', label="inline block phase mapping")
    require(render_js, 'const sourceLabel = handoffVisible ? "handoff" : "sse";', label="inline block source mapping")
    require(render_js, "const renderedItems = items", label="transcript render item join")
    require(render_js, 'dom.conversationTimeline.innerHTML = renderedItems + inlineSessionBlock;', label="transcript tail inline block render")
    require_absent(render_js, 'dom.conversationTimeline.innerHTML = inlineSessionBlock + items', label="legacy inline block prepended render")
    require_absent(render_js, "In Flight Assistant", label="duplicate accepted status block copy")
    require_absent(render_js, 'return { label: "GENERATING", tone: "neutral" };', label="legacy generating handoff chip")
    require(styles_css, ".session-strip-draft", label="composer activity draft CSS")
    require(styles_css, ".composer-toolbar", label="chat-style composer toolbar CSS")
    require(styles_css, ".composer-footer", label="chat-first composer footer CSS")
    require(styles_css, ".composer-send-primary", label="primary send button CSS")
    require(styles_css, ".composer-utility-menu", label="composer utility menu CSS")
    require(styles_css, ".composer-utility-toggle-button", label="composer utility toggle button CSS")
    require(styles_css, ".composer-secondary-action", label="secondary composer action CSS")
    require(styles_css, ".composer-utility-cluster", label="composer utility cluster CSS")
    require(styles_css, ".composer-utility-toggle", label="composer utility toggle CSS")
    require(styles_css, ".composer-hint-compact", label="compact composer hint CSS")
    require(styles_css, ".sidebar-primary-nav", label="mobile conversation-first nav section CSS")
    require(styles_css, ".sidebar-app-summary", label="compact app summary CSS")
    require(styles_css, ".sidebar-app-summary-copy", label="compact app summary copy CSS")
    require(styles_css, ".sidebar-ops-details", label="mobile operator section CSS")
    require(styles_css, ".nav-ops-summary", label="mobile operator summary CSS")
    require(styles_css, ".nav-ops-content", label="mobile operator content CSS")
    require(styles_css, '.sidebar[data-mobile-nav-priority="conversations"] .sidebar-primary-nav[data-nav-primary="threads"]', label="mobile nav primary section priority CSS")
    require(styles_css, '.sidebar[data-mobile-nav-priority="conversations"] .sidebar-ops-details[data-nav-secondary="ops"]', label="mobile nav secondary section CSS")
    require(styles_css, ".sidebar-ops-details[open] .nav-ops-summary::after", label="mobile operator summary state CSS")
    require(styles_css, "order: 1;", label="conversation rail primary order CSS")
    require(styles_css, "order: 2;", label="operator rail secondary order CSS")
    require(styles_css, ".jump-to-latest", label="jump-to-latest CSS")
    require(styles_css, ".jump-to-latest-chip", label="jump-to-latest chip CSS")
    require(styles_css, ".jump-to-latest-copy", label="jump-to-latest copy CSS")
    require(styles_css, '.jump-to-latest[data-follow-state="new"] .jump-to-latest-chip', label="jump-to-latest new state CSS")
    require(styles_css, '.jump-to-latest[data-follow-state="paused"] .jump-to-latest-chip', label="jump-to-latest paused state CSS")
    require(styles_css, ".timeline-transition", label="thread transition CSS")
    require(styles_css, ".timeline-transition-chip", label="thread transition chip CSS")
    require(styles_css, "position: sticky;", label="sticky footer CSS")
    require(styles_css, "env(safe-area-inset-bottom)", label="safe-area footer padding CSS")
    require(styles_css, ".mobile-nav-toggle", label="mobile nav button CSS")
    require(styles_css, ".thread-scroller:focus-visible", label="conversation surface focus ring CSS")
    require_absent(index_html, 'id="conversation-live-status"', label="legacy live badge DOM")
    require_absent(index_html, 'id="live-run-row"', label="legacy live run row DOM")
    require_absent(index_html, 'id="append-stream-strip"', label="legacy append stream DOM")
    require_absent(index_html, 'id="autonomy-context-strip"', label="header autonomy strip DOM")
    require_absent(index_html, 'id="hero-conversation-state"', label="header conversation status DOM")
    require_absent(index_html, 'id="hero-job-state"', label="header job status DOM")
    require_absent(index_html, 'id="hero-app-name"', label="legacy app-centric header title DOM")
    require_absent(index_html, "<h3>메시지 보내기</h3>", label="prose-heavy composer heading DOM")
    require_absent(index_html, "sidebar-inspector", label="legacy sidebar inspector")
    require_absent(index_html, "sidebar-footer", label="legacy sidebar footer")
    require_absent(index_html, 'class="autonomy-rail"', label="legacy standalone autonomy rail DOM")
    print("ok: ops desktop secondary panel, footer dock, session strip, append SSE wiring, and mobile nav drawer are present")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except AssertionError as error:
        print(f"verification failed: {error}", file=sys.stderr)
        raise SystemExit(1)
