#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]


def read(relative_path: str) -> str:
    return (ROOT / relative_path).read_text(encoding="utf-8")


def require(content: str, needle: str, *, label: str) -> None:
    if needle not in content:
        raise AssertionError(f"missing {label}: {needle}")


def require_absent(content: str, needle: str, *, label: str) -> None:
    if needle in content:
        raise AssertionError(f"unexpected {label}: {needle}")


def main() -> int:
    app_js = read("examples/generated_apps/codex-ops-console/web/app.js")
    api_js = read("examples/generated_apps/codex-ops-console/web/ops-api.js")
    conversations_js = read("examples/generated_apps/codex-ops-console/web/ops-conversations.js")
    jobs_js = read("examples/generated_apps/codex-ops-console/web/ops-jobs.js")
    render_js = read("examples/generated_apps/codex-ops-console/web/ops-render.js")
    store_js = read("examples/generated_apps/codex-ops-console/web/ops-store.js")
    api_runtime_context_py = read("src/codex_factory_runtime/api_runtime_context.py")
    api_routes_py = read("src/codex_factory_runtime/api_routes.py")
    deployed_console_sh = read("scripts/verify_deployed_console.sh")
    deployed_workspace_py = read("scripts/verify_deployed_workspace_gate.py")
    styles_css = read("examples/generated_apps/codex-ops-console/web/styles.css")
    index_html = read("examples/generated_apps/codex-ops-console/web/index.html")
    autonomy_detail_index = index_html.index('id="autonomy-detail"')
    recent_thread_rail_index = index_html.index('id="recent-thread-rail"')
    thread_scroller_index = index_html.index('id="thread-scroller"')
    footer_dock_index = index_html.index('id="conversation-footer-dock"')
    composer_shell_index = index_html.index('class="composer-shell"')
    session_strip_index = index_html.index('id="session-strip"')
    draft_status_index = index_html.index('id="draft-status"')
    composer_footer_index = index_html.index('class="composer-footer"')
    sidebar_index = index_html.index('id="nav-sheet"')
    main_stage_index = index_html.index('<section class="main-stage panel" data-primary-surface="conversation">')
    secondary_panel_index = index_html.index('id="secondary-panel"')
    if not (secondary_panel_index < autonomy_detail_index):
        raise AssertionError("detailed autonomy summary is no longer reachable through the secondary panel")
    if not (recent_thread_rail_index < thread_scroller_index < footer_dock_index < composer_shell_index):
        raise AssertionError("recent-thread rail, thread scroller, and footer dock order no longer preserves the conversation workspace")
    if not (composer_shell_index < session_strip_index < draft_status_index < composer_footer_index):
        raise AssertionError("composer-adjacent activity bar no longer sits inside the composer shell ahead of footer actions")
    if not (sidebar_index < main_stage_index < secondary_panel_index):
        raise AssertionError("desktop workspace no longer uses sidebar, main stage, then secondary panel order")

    require(api_js, "/api/internal/conversations/${conversationId}/append-stream", label="append SSE URL builder")
    require(api_js, 'url.searchParams.set("after", String(afterAppendId));', label="append SSE resume cursor query")
    require(conversations_js, "new window.EventSource(", label="EventSource wiring")
    require(conversations_js, "internalConversationAppendStreamUrl(conversationId, { afterAppendId: resumeCursor })", label="EventSource resume URL builder")
    require(conversations_js, 'addEventListener("session.bootstrap"', label="session bootstrap event listener")
    require(conversations_js, 'addEventListener("conversation.append"', label="append event listener")
    require(conversations_js, "appendEnvelope.conversation_id !== activeConversationId", label="cross-conversation guard")
    require(conversations_js, "appendId <= Number(state.appendStream?.lastAppendId || 0)", label="append_id dedupe")
    require(conversations_js, 'state.appendStream.status = isResumeAttempt ? "reconnecting" : "connecting";', label="connecting state")
    require(conversations_js, 'state.appendStream.status = "live"', label="live state")
    require(conversations_js, 'state.appendStream.status = "reconnecting"', label="reconnecting state")
    require(conversations_js, 'state.appendStream.attachMode = isResumeAttempt ? "sse-resume" : "awaiting-bootstrap";', label="attach mode awaiting bootstrap state")
    require(conversations_js, 'state.appendStream.attachMode = "snapshot-fallback"', label="attach mode snapshot fallback state")
    require(conversations_js, 'state.appendStream.attachMode = "sse-resume"', label="attach mode resume state")
    require(conversations_js, 'state.appendStream.attachMode = String(payload.attach_mode || (isResumeAttempt ? "sse-resume" : "sse-bootstrap"));', label="attach mode bootstrap state")
    require(conversations_js, 'state.appendStream.bootstrapVersion = String(payload.version || "")', label="bootstrap version state")
    require(conversations_js, 'state.appendStream.resumeMode = "awaiting-resume"', label="resume awaiting state")
    require(conversations_js, 'state.appendStream.resumeMode = isResumeAttempt ? "resuming" : "bootstrap";', label="resume active state")
    require(conversations_js, 'state.appendStream.resumeMode = isResumeAttempt ? "resumed" : "bootstrap";', label="resume completed state")
    require(conversations_js, 'state.appendStream.resumeMode = "fallback"', label="resume fallback state")
    require(conversations_js, 'state.appendStream.resumeCursor = Math.max(Number(payload.resume_from_append_id || resumeCursor || 0), 0);', label="resume cursor bootstrap state")
    require(conversations_js, "normalizeSessionPhase", label="selected-thread phase normalization helper")
    require(conversations_js, "appendEnvelope.session_phase", label="append envelope session phase payload")
    require(conversations_js, "payload.session_phase", label="bootstrap session phase payload")
    require(conversations_js, "normalizeAutonomySummary", label="autonomy summary normalization helper")
    require(conversations_js, "hydrateAutonomySummary", label="autonomy summary hydration helper")
    require(conversations_js, "isSelectedThreadAutonomyAuthoritative", label="selected-thread autonomy authority helper")
    require(conversations_js, "shouldAllowGoalsPollingFallback", label="selected-thread goals fallback gate")
    require(conversations_js, "payload.autonomy_summary || payload.conversation?.autonomy_summary", label="bootstrap autonomy summary hydration")
    require(conversations_js, "conversation.autonomy_summary", label="snapshot autonomy summary hydration")
    require(conversations_js, "scheduleAppendStreamResume", label="resume scheduler helper")
    require(conversations_js, "transitionAppendStreamToFallback", label="explicit append stream fallback helper")
    require(conversations_js, "MAX_RESUME_ATTEMPTS = 3", label="bounded resume attempts")
    require(conversations_js, 'delivery_source: "sse"', label="SSE provenance tagging")
    require(conversations_js, "state.appendStream.transport = \"sse\"", label="SSE transport evidence")
    require(conversations_js, "syncConversationCardState", label="conversation card state sync helper")
    require(conversations_js, "showPendingOutgoing", label="pending outgoing render helper")
    require(conversations_js, "clearPendingOutgoing", label="pending outgoing clear helper")
    require(conversations_js, "showPendingAssistant", label="pending assistant handoff helper")
    require(conversations_js, "shouldClearPendingOutgoing", label="pending handoff clear predicate")
    require(conversations_js, "data-conversation-live-state", label="conversation card live state marker")
    require(conversations_js, "conversationPreview", label="conversation preview helper")
    require(conversations_js, "truncatePreview", label="bounded conversation preview helper")
    require(conversations_js, "latestMessagePreview", label="preferred message preview helper")
    require(conversations_js, "eventPreview", label="event preview helper")
    require(conversations_js, "snapshotThreadState", label="conversation snapshot state helper")
    require(conversations_js, "snapshotThreadLabel", label="conversation snapshot label helper")
    require(conversations_js, "compactConversationLabel", label="conversation live label helper")
    require(conversations_js, "liveOwnerLabel", label="selected live owner label helper")
    require(conversations_js, "liveOwnerDetail", label="selected live owner detail helper")
    require(conversations_js, "liveOwnerFollowLabel", label="selected live owner follow helper")
    require(conversations_js, "liveOwnerState", label="selected live owner state helper")
    require(conversations_js, "liveOwnerMarkerLabel", label="selected live owner marker helper")
    require(conversations_js, "renderRecentThreadRail", label="recent-thread rail render helper")
    require(conversations_js, "RECENT_THREAD_LIMIT = 4", label="bounded recent-thread rail limit")
    require(conversations_js, "state.recentConversations = recentConversations.map", label="recent-thread state caching")
    require(conversations_js, "data-recent-thread-chip", label="recent-thread chip DOM")
    require(conversations_js, "data-recent-thread-marker", label="recent-thread marker DOM")
    require(conversations_js, "data-recent-thread-owner", label="recent-thread owner DOM")
    require(conversations_js, "data-recent-thread-state", label="recent-thread state DOM")
    require(conversations_js, "data-recent-thread-follow", label="recent-thread follow DOM")
    require(conversations_js, 'chip.dataset.liveOwner = isSelected && showLiveMirror ? "true" : "false";', label="recent-thread live owner dataset")
    require(conversations_js, 'stateLabel.textContent = isSwitching', label="recent-thread switching state wiring")
    require(conversations_js, 'follow.textContent = isSwitching ? "ATTACH" : isSelected && showLiveMirror ? liveFollowLabel : "";', label="recent-thread attach follow wiring")
    require(conversations_js, 'owner.textContent = "OWNER";', label="recent-thread owner label")
    require(conversations_js, "syncActiveSessionRow", label="sticky active session row helper")
    require(conversations_js, "threadTitleForConversation", label="thread switch title helper")
    require(conversations_js, "startThreadTransition", label="thread transition start helper")
    require(conversations_js, "clearThreadTransition", label="thread transition clear helper")
    require(conversations_js, 'state.currentConversationId = "";', label="thread switch clears current conversation before attach")
    require(conversations_js, "data-conversation-session", label="conversation session marker DOM")
    require(conversations_js, "data-conversation-live-owner-row", label="selected conversation live owner row DOM")
    require(conversations_js, "data-conversation-live-detail", label="selected conversation live detail DOM")
    require(conversations_js, "data-conversation-live-follow", label="selected conversation live follow DOM")
    require(conversations_js, "data-snapshot-thread-state", label="conversation snapshot state DOM")
    require(conversations_js, "data-snapshot-state-label", label="conversation snapshot state label DOM")
    require(conversations_js, 'data-preview-lines="1"', label="single-line conversation preview DOM")
    require(conversations_js, "dom.threadScroller?.dataset.sessionPresentation", label="left rail uses session presentation state")
    require(conversations_js, 'const selectedThreadSseOwned = selectedConversationId && selectedConversationId === liveConversationId && renderSource === "sse";', label="selected row sse ownership guard")
    require(conversations_js, 'marker.textContent = isSelected && showLiveMirror ? liveOwnerMarkerLabel(liveOwnerStateLabel) : "NOW";', label="selected live owner marker label")
    require(conversations_js, 'card.dataset.liveOwnerState = isSelected && showLiveMirror ? liveOwnerStateLabel : "idle";', label="selected live owner state dataset")
    require(conversations_js, 'liveDetailRow.dataset.liveOwnerState = isSelected && showLiveMirror ? liveOwnerStateLabel : "idle";', label="selected live owner row state dataset")
    require(conversations_js, 'liveFollowText.dataset.liveOwnerState = isSelected && showLiveMirror ? liveOwnerStateLabel : "idle";', label="selected live follow state dataset")
    require(conversations_js, "sessionMarker.hidden = !isSelected", label="selected thread session marker visibility")
    require(conversations_js, 'card.dataset.liveOwner = isSelected && showLiveMirror ? "true" : "false";', label="selected live owner dataset")
    require(conversations_js, "liveDetailRow.hidden = !(isSelected && showLiveMirror)", label="selected live detail visibility")
    require(conversations_js, "liveState.hidden = isSelected", label="selected thread snapshot badge hiding")
    require(conversations_js, 'dom.activeSessionRow.dataset.activeSessionState = visible ? rowState : "idle";', label="active session row state dataset")
    require(conversations_js, 'dom.activeSessionRow.dataset.activeSessionConversationId = visible ? conversationId : "";', label="active session row conversation dataset")
    require(conversations_js, 'dom.activeSessionRow.dataset.activeSessionFollow = visible ? followLabel.toLowerCase() : "idle";', label="active session row follow dataset")
    require(conversations_js, 'dom.activeSessionRow.dataset.activeSessionOwned = visible ? String(rowOwned) : "false";', label="active session row ownership dataset")
    require(conversations_js, 'dom.activeSessionRow.dataset.activeSessionSource = visible ? rowSource : "none";', label="active session row source dataset")
    require(conversations_js, 'dom.activeSessionRow.dataset.activeSessionPhase = visible ? rowPhase : "IDLE";', label="active session row phase dataset")
    require(conversations_js, 'dom.activeSessionRow.dataset.activeSessionUnseenCount = String(visible ? rowUnseenCount : 0);', label="active session row unseen dataset")
    require(conversations_js, "const authoritativeSelectedAttach =", label="selected-thread attach authority gate")
    require(conversations_js, "if (authoritativeSelectedAttach) {", label="selected-thread attach authority short circuit")
    require(conversations_js, 'const summaryLiveOwned = String(dom.sessionSummaryRow?.dataset.liveSessionOwned || "false") === "true";', label="active session canonical ownership source")
    require(conversations_js, 'const summaryLiveSource = String(dom.sessionSummaryRow?.dataset.liveSessionSource || "none");', label="active session canonical source dataset")
    require(conversations_js, 'const summaryLiveState = String(dom.sessionSummaryRow?.dataset.liveSessionState || "idle");', label="active session canonical state dataset")
    require(conversations_js, 'const summaryLiveReason = String(dom.sessionSummaryRow?.dataset.liveSessionReason || "idle");', label="active session canonical reason dataset")
    require(conversations_js, 'const summaryStateLabel = String(dom.sessionSummaryState?.textContent || "").trim().toUpperCase();', label="active session canonical phase label source")
    require(conversations_js, 'const sessionIndicatorLabel = String(dom.sessionLiveIndicator?.textContent || "").trim().toUpperCase();', label="active session canonical label source")
    require(conversations_js, 'const healthySelectedSessionMirror =', label="active session healthy mirror gate")
    require(conversations_js, 'summaryLiveSource === "sse"', label="active session healthy sse source gate")
    require(conversations_js, 'sessionIndicatorLabel === "SSE OWNER"', label="active session healthy label gate")
    require(conversations_js, 'stateLabel = summaryStateLabel || liveRunPhase || "LIVE";', label="active session mirrored phase label")
    require(conversations_js, 'rowState = summaryLiveState === "paused" ? "paused" : "live";', label="active session mirrored state mapping")
    require(conversations_js, 'followLabel = jumpVisible ? "NEW" : summaryLiveState === "paused" ? "PAUSED" : "LIVE";', label="active session mirrored follow mapping")
    require(conversations_js, 'rowSource = summaryLiveSource;', label="active session mirrored source")
    require(conversations_js, 'rowPhase = stateLabel;', label="active session mirrored phase")
    require(conversations_js, 'rowUnseenCount = jumpVisible ? Math.max(Number(unseenCount || 0), 0) : 0;', label="active session unseen count mirror")
    require(conversations_js, '`selected thread · ${stateLabel.toLowerCase()} · ${rowUnseenCount} new`', label="active session unseen meta copy")
    require(conversations_js, '`selected thread · ${stateLabel.toLowerCase()} · follow paused`', label="active session paused meta copy")
    require(conversations_js, '`selected thread · ${stateLabel.toLowerCase()} · sse owner`', label="active session healthy meta copy")
    require_absent(conversations_js, 'rowSource = "thread-transition";', label="legacy active session switching source")
    require_absent(conversations_js, 'selected-thread-handoff', label="legacy active session handoff source")
    require(conversations_js, "syncSelectedSessionFromLiveAppend", label="selected-thread live append sync helper")
    require(conversations_js, "const liveJobId = String(livePayload.job_id || \"\").trim();", label="live append job id extraction")
    require(conversations_js, "state.currentJobId = liveJobId;", label="live append selected-thread job id authority")
    require(conversations_js, "conversation.latest_job_id = liveJobId;", label="live append conversation job id authority")
    require(conversations_js, "shouldProjectAutonomySummaryFromLiveAppend", label="autonomy summary append projection helper")
    require(conversations_js, "projectAutonomySummaryFromLiveAppend", label="autonomy summary live projection helper")
    require(conversations_js, "liveJobMetaLabel", label="live append job meta helper")
    require(conversations_js, "const projectedAutonomySummary = projectAutonomySummaryFromLiveAppend(kind, payload);", label="append-driven autonomy summary projection")
    require(conversations_js, "state.autonomySummary = projectedAutonomySummary;", label="append-driven autonomy summary state update")
    require(conversations_js, 'if (!shouldAllowGoalsPollingFallback({ conversationId })) {', label="healthy selected-thread goals fallback suppression")
    require(conversations_js, 'await refreshGoalSummary({ conversationId: conversation.conversation_id });', label="conversation-scoped autonomy fallback refresh")
    require_absent(conversations_js, "refreshGoalSummary().catch(() => {});", label="legacy append-driven autonomy summary refetch")
    require(conversations_js, "setJobMeta(dom, immediateMeta);", label="append-driven job meta refresh")
    require(conversations_js, 'type === "job.running"', label="job running append refresh mapping")
    require(conversations_js, 'type === "proposal.ready"', label="proposal ready append refresh mapping")
    require(conversations_js, 'type.startsWith("goal.review.phase.")', label="review append refresh mapping")
    require(conversations_js, 'type.startsWith("goal.verify.phase.")', label="verify append refresh mapping")
    require(conversations_js, "scheduleAppendStreamResume(conversationId, Math.max(reconnectAttempt, 0) + 1);", label="reconnect resume scheduling")
    require_absent(
        conversations_js,
        'state.appendStream.status = "reconnecting";\n      state.appendStream.attachMode = "snapshot-fallback";\n      ensurePollingForJob();',
        label="legacy reconnect snapshot fallback",
    )
    require(store_js, "export function isAppendStreamAuthoritative", label="append stream authoritative helper")
    require(store_js, "export function isSelectedThreadSessionOwned", label="selected-thread session ownership helper")
    require(store_js, 'phaseValue === "LIVE"', label="selected-thread session live phase guard")
    require(store_js, 'phaseValue === "PROPOSAL"', label="selected-thread session proposal phase guard")
    require(store_js, 'phaseValue === "REVIEW"', label="selected-thread session review phase guard")
    require(store_js, 'phaseValue === "VERIFY"', label="selected-thread session verify phase guard")
    require(store_js, 'phaseValue === "READY"', label="selected-thread session ready phase guard")
    require(store_js, 'phaseValue === "APPLIED"', label="selected-thread session applied phase guard")
    require(store_js, 'appendStream.status === "connecting" || appendStream.status === "live"', label="append stream authoritative connecting-or-live guard")
    require(jobs_js, "isAppendStreamAuthoritative", label="job polling authoritative helper wiring")
    require(jobs_js, "isSelectedThreadSessionOwned", label="job polling selected-thread session ownership helper wiring")
    require(jobs_js, "state.currentConversationId && isSelectedThreadSessionOwned(state, state.currentConversationId)", label="polling suppression while selected-thread session is sse-owned")
    require(jobs_js, "stopPolling();\n      return;", label="polling early exit while selected-thread session is sse-owned")
    require(conversations_js, 'return "CONNECT";', label="compact connecting rail label")
    require(conversations_js, 'return "RESUME";', label="compact reconnect rail label")
    require(conversations_js, 'return "LIVE";', label="compact live rail label")
    require(conversations_js, 'return "FAILED";', label="compact failed rail label")
    require(conversations_js, 'return "READY";', label="compact ready rail label")
    require(conversations_js, 'return "VERIFY";', label="compact verify rail label")
    require(conversations_js, 'return "REVIEW";', label="compact review rail label")
    require(conversations_js, 'return "PROPOSAL";', label="compact proposal rail label")
    require(conversations_js, 'return "WAITING";', label="compact waiting rail label")
    require(conversations_js, 'return "ACTIVE";', label="compact active rail label")
    require(conversations_js, 'return "DONE";', label="compact done rail label")
    require(conversations_js, 'return "IDLE";', label="compact idle rail label")
    require(conversations_js, "메시지가 접수되어 첫 응답을 기다리는 중입니다.", label="accepted event preview copy")
    require(conversations_js, "작업이 대기열에 올라 있습니다.", label="queued event preview copy")
    require(conversations_js, "최근 작업이 현재 진행 중입니다.", label="running event preview copy")
    require(conversations_js, "제안 단계가 진행 중입니다.", label="proposal event preview copy")
    require(conversations_js, "리뷰 단계가 진행 중입니다.", label="review event preview copy")
    require(conversations_js, "검증 단계가 진행 중입니다.", label="verify event preview copy")
    require(conversations_js, "자동 적용 단계가 진행 중입니다.", label="auto-apply event preview copy")
    require(conversations_js, 'return "HANDOFF";', label="selected live owner handoff marker label")
    require(conversations_js, 'return "NEW";', label="selected live owner new marker label")
    require(conversations_js, 'return "PAUSED";', label="selected live owner paused marker label")
    require(conversations_js, 'return "OWNER";', label="selected live owner session chip label")
    require(jobs_js, "!isAppendStreamAuthoritative(state, state.currentConversationId)", label="polling refetch skip while append stream is authoritative")
    require(render_js, "renderSessionSummary", label="header session summary helper")
    require(render_js, "composerOwnerState", label="composer owner state helper")
    require(render_js, "composerTransportState", label="composer transport state helper")
    require(render_js, "syncComposerOwnership", label="composer ownership sync helper")
    require(render_js, "compactTargetLabel", label="compact target label helper")
    require(render_js, "summaryHint", label="summary hint helper")
    require(render_js, 'pathLabel = "SWITCHING"', label="summary switching path label")
    require(render_js, 'pathLabel = "HANDOFF"', label="summary handoff path label")
    require(render_js, 'pathLabel = "SSE"', label="summary sse path label")
    require(render_js, 'pathLabel = "DEGRADED"', label="summary degraded path label")
    require(render_js, 'label: "SWITCHING"', label="composer switching label")
    require(render_js, 'label: "HANDOFF"', label="composer handoff label")
    require(render_js, 'label: "READY"', label="composer ready label")
    require(render_js, 'copy: "ATTACH"', label="composer switching compact copy")
    require(render_js, 'pendingOutgoing.status === "sending-user"', label="composer sending compact copy guard")
    require(render_js, '? "SEND"', label="composer sending compact copy")
    require(render_js, ': "ACCEPTED"', label="composer accepted compact copy")
    require(render_js, 'copy: "LOCKED"', label="composer ready compact copy")
    require(render_js, 'copy: "SELECT"', label="composer idle compact copy")
    require(render_js, 'dom.sendRequestButton.dataset.composerBlocked = owner.blocked ? "true" : "false";', label="composer blocked dataset")
    require(render_js, 'dom.sendRequestButton.dataset.composerOwnerState = owner.state;', label="composer owner state dataset")
    require(render_js, 'dom.sendRequestButton.dataset.composerBlockedReason = owner.blockedReason;', label="composer blocked reason dataset")
    require(render_js, 'const mergedStripVisible = Boolean(dom.sessionStrip && !dom.sessionStrip.hidden);', label="composer owner row merged strip visibility")
    require(render_js, 'dom.composerOwnerRow.dataset.composerOwnerMerged = mergedStripVisible ? "true" : "false";', label="composer owner merged dataset")
    require(render_js, 'dom.composerOwnerRow.hidden = mergedStripVisible;', label="composer owner row hidden when strip active")
    require(render_js, 'dom.sessionStrip.dataset.composerState = ownerState.state;', label="composer strip state dataset")
    require(render_js, 'dom.sessionStrip.dataset.composerTransport = transportState.key;', label="composer strip transport dataset")
    require(render_js, 'dom.sessionStrip.dataset.composerTransportSource = transportState.source;', label="composer strip transport source dataset")
    require(render_js, 'dom.sessionStrip.dataset.composerTransportOwned = transportState.owned ? "true" : "false";', label="composer strip transport owned dataset")
    require(render_js, 'dom.sessionStrip.dataset.composerTransportReason = transportState.reason;', label="composer strip transport reason dataset")
    require(render_js, 'dom.sessionStrip.dataset.composerTargetConversationId = ownerState.conversationId;', label="composer strip target dataset")
    require(render_js, "const proposalState = proposalChip(liveRun);", label="composer strip proposal chip helper wiring")
    require(render_js, 'label: "ATTACH"', label="composer strip attach label")
    require(render_js, 'label: "SNAPSHOT"', label="composer strip snapshot label")
    require(render_js, 'label: "POLLING"', label="composer strip polling label")
    require(render_js, 'label: "RECONNECT"', label="composer strip reconnect label")
    require(render_js, 'proposalState.label !== "NONE"', label="composer strip proposal chip visibility")
    require(render_js, 'dom.sessionSummaryScope.textContent = compactTargetLabel(', label="selected-thread summary scope copy")
    require(render_js, 'dom.sessionSummaryRow.dataset.summaryPath = pathLabel.toLowerCase();', label="session summary path dataset")
    require(render_js, 'dom.sessionSummaryRow.dataset.summaryState = stateLabel.toLowerCase();', label="session summary state dataset")
    require(render_js, 'dom.sessionSummaryRow.dataset.followState = sessionIndicator.state;', label="session summary follow-state dataset")
    require(render_js, "selectedThreadLiveSessionIndicator", label="header live-session indicator helper")
    require(render_js, "latestSessionIndicatorEvent", label="header live-session event helper")
    require(render_js, 'dom.sessionSummaryRow.dataset.liveSessionState = sessionIndicator.state;', label="header live-session state dataset")
    require(render_js, 'dom.sessionSummaryRow.dataset.liveSessionSource = sessionIndicator.source;', label="header live-session source dataset")
    require(render_js, 'dom.sessionSummaryRow.dataset.liveSessionReason = sessionIndicator.reason;', label="header live-session reason dataset")
    require(render_js, 'dom.sessionSummaryRow.dataset.liveSessionOwned = sessionIndicator.owned ? "true" : "false";', label="header live-session ownership dataset")
    require(render_js, 'const compactHeaderChromeHidden = Boolean(conversationId || threadTransition.targetConversationId);', label="compact header chrome visibility gate")
    require(render_js, 'dom.sessionSummaryRow.hidden = compactHeaderChromeHidden;', label="header summary row hidden")
    require(render_js, 'dom.sessionLiveIndicator.hidden = compactHeaderChromeHidden || !sessionIndicator.visible;', label="header live-session visibility wiring")
    require(render_js, "dom.threadPhaseChip.hidden = compactHeaderChromeHidden;", label="header phase chip hidden")
    require(render_js, 'dom.sessionLiveIndicator.dataset.liveSessionTone = sessionIndicator.tone;', label="header live-session tone dataset")
    require(render_js, 'dom.sessionLiveIndicator.dataset.liveSessionSource = sessionIndicator.source;', label="header indicator source dataset")
    require(render_js, 'dom.sessionLiveIndicator.dataset.liveSessionOwned = sessionIndicator.owned ? "true" : "false";', label="header indicator ownership dataset")
    require(render_js, 'dom.sessionLiveIndicator.dataset.liveSessionReason = sessionIndicator.reason;', label="header indicator reason dataset")
    require(render_js, 'label: "SSE OWNER"', label="header live ownership label")
    require(render_js, 'label: "RECONNECT"', label="header live-session reconnect label")
    require(render_js, 'label: "POLLING"', label="header live-session polling label")
    require(render_js, "phaseDetailCopy", label="phase detail copy helper")
    require(render_js, "compactPhaseDetailCopy", label="compact phase detail copy helper")
    require(render_js, 'dom.threadPhaseChip.dataset.threadPhaseDetail = liveRun?.visible ? phaseDetailCopy(liveRun) : "idle";', label="header phase detail dataset")
    require(render_js, 'dom.threadPhaseChip.title = liveRun?.visible ? phaseDetailCopy(liveRun) : "현재 활성 세션이 없습니다.";', label="header phase detail title copy")
    require(render_js, 'reason: followPaused ? "selected-thread-follow-paused" : "selected-thread-following"', label="header live-follow reason")
    require(render_js, 'reason: sessionRotationDetected ? "session-rotation" : retrying ? "retrying" : "polling-fallback"', label="header live-session degraded reason")
    require(render_js, 'type === "codex.exec.retrying"', label="header live-session retry event mapping")
    require(render_js, 'summaryHint("SSE OWNER", "FOLLOW PAUSED")', label="summary paused ownership copy")
    require(render_js, ': compactPhaseDetailCopy(liveRun, stateLabel);', label="summary live phase compact copy")
    require(render_js, "deriveLiveRunState", label="inline live run state derivation")
    require(render_js, "selectedThreadSessionPhase", label="selected-thread authoritative phase helper")
    require(render_js, 'state: "sending"', label="local pending sending state")
    require(render_js, 'state: "generating"', label="assistant placeholder generating state")
    require(render_js, 'state: "proposal-phase"', label="proposal phase live run state")
    require(render_js, 'state: "review-phase"', label="review phase live run state")
    require(render_js, 'state: "verify-phase"', label="verify phase live run state")
    require(render_js, 'state: "proposal-ready"', label="proposal ready live run state")
    require(render_js, 'state: "applied"', label="applied live run state")
    require(render_js, 'state: sessionPhase.value === "LIVE" ? "live" : "unknown"', label="neutral live run state")
    require(render_js, 'phase: "PROPOSAL"', label="proposal phase label")
    require(render_js, 'phase: "REVIEW"', label="review phase label")
    require(render_js, 'phase: "VERIFY"', label="verify phase label")
    require(render_js, 'phase: "READY"', label="proposal ready phase label")
    require(render_js, 'phase: "APPLIED"', label="applied phase label")
    require(render_js, 'phase: sessionPhase.value === "LIVE" ? "LIVE" : "UNKNOWN"', label="neutral live phase label")
    require(render_js, 'goal.proposal.phase.started', label="proposal phase event mapping")
    require(render_js, 'goal.review.phase.started', label="review phase event mapping")
    require(render_js, 'goal.verify.phase.started', label="verify phase event mapping")
    require(render_js, "renderSessionStrip", label="unified session strip renderer")
    require(render_js, "renderThreadTransition", label="thread transition render helper")
    require(render_js, 'data-thread-transition="loading"', label="thread transition DOM")
    require(render_js, 'dom.conversationTimeline.innerHTML = isThreadTransition', label="thread transition placeholder render branch")
    require(render_js, '? renderThreadTransition(currentState)', label="thread transition placeholder render path")
    require(render_js, ": '<p class=\"timeline-empty\">새 대화를 만들면 요청과 이벤트가 여기 쌓입니다.</p>';",
            label="empty state limited to non-transition path")
    require(render_js, 'conversationState: isThreadTransition ? "새 대화 스냅샷을 연결하는 중입니다." : "아직 대화 세션이 없습니다.",', label="thread transition conversation state copy")
    require(render_js, 'threadTitle: isThreadTransition ? String(threadTransition.targetTitle || "대화 전환 중") : "새 대화를 시작하세요",', label="thread transition title copy")
    require(render_js, 'phase: isThreadTransition ? "UNKNOWN" : currentState.currentJobId ? "RUNNING" : "IDLE",', label="thread transition neutral phase")
    require(render_js, 'source: isThreadTransition ? "thread-transition" : "none",', label="thread transition neutral phase source")
    require(render_js, 'dom.threadScroller.dataset.threadTransitionState = isThreadTransition ? "loading" : "idle";', label="thread transition state dataset")
    require(render_js, 'dom.threadScroller.dataset.threadTransitionConversationId = isThreadTransition', label="thread transition conversation dataset")
    require(render_js, 'renderSessionStrip(dom, currentState, null);', label="thread transition composer shell render path")
    require(render_js, 'syncComposerOwnership(dom, currentState, null);', label="thread transition composer owner switching path")
    require(render_js, 'conversationId: isThreadTransition ? String(threadTransition.targetConversationId || "") : "",', label="thread transition live-follow target reset")
    require(render_js, 'presentation === "sending"', label="sending presentation state")
    require(render_js, 'data-pending-local="true"', label="pending local timeline marker")
    require(render_js, 'data-pending-assistant="true"', label="pending assistant timeline marker")
    require(render_js, "local-pending", label="pending local render source")
    require(render_js, "local-assistant-placeholder", label="assistant placeholder render source")
    require(render_js, "pendingHandoffState", label="single pending handoff render helper")
    require(render_js, 'stage: "pending-user"', label="pending user handoff stage")
    require(render_js, 'stage: "pending-assistant"', label="pending assistant handoff stage")
    require(render_js, "selectedThreadSseOwned", label="pending assistant selected-thread SSE ownership guard")
    require(render_js, "pendingOutgoing.status === \"awaiting-assistant\" &&", label="awaiting-assistant ownership render guard")
    require(render_js, 'const handoffVisible = handoffState.stage === "pending-assistant" && selectedThreadSseOwned;', label="inline handoff visibility guard")
    require(render_js, "const liveVisible =", label="inline live visibility guard")
    require(render_js, 'renderSource === "sse"', label="inline live render-source guard")
    require(render_js, 'status === "live"', label="inline live healthy-status guard")
    require(render_js, "pendingUserCount", label="pending user count dataset state")
    require(render_js, "pendingAssistantCount", label="pending assistant count dataset state")
    require(render_js, "handoffState.items", label="single pending handoff item render wiring")
    require(render_js, 'dom.threadScroller.dataset.pendingHandoffStage = handoffState.stage', label="pending handoff stage dataset")
    require(render_js, 'dom.threadScroller.dataset.pendingUserCount = String(handoffState.pendingUserCount)', label="pending user count dataset")
    require(render_js, 'dom.threadScroller.dataset.pendingAssistantCount = String(handoffState.pendingAssistantCount)', label="pending assistant count dataset")
    require(conversations_js, "syncSelectedAppSession", label="selected app session sync helper")
    require(conversations_js, 'option.dataset.sessionId = app.session_id || "";', label="selected app session id option dataset")
    require(conversations_js, "rotationDetected", label="selected app session rotation detection")
    require(jobs_js, "renderJobActivity(dom, state.conversationCache, state.currentJobId, payload, state);", label="job panel receives current state for SSE ownership")
    require(render_js, "autonomyDetailMeta", label="secondary panel autonomy detail meta wiring")
    require(render_js, "syncAutonomyDetailSurface", label="secondary autonomy surface sync helper")
    require(render_js, 'autonomyCard.hidden = hideForHealthySelectedThread;', label="healthy selected-thread autonomy card suppression")
    require(render_js, 'autonomyCard.dataset.autonomySurface = hideForHealthySelectedThread ? "center-lane" : "secondary-detail";', label="autonomy card surface dataset")
    require(render_js, 'dom.autonomyDetail.dataset.surface = hideForHealthySelectedThread ? "center-lane" : "secondary-detail";', label="autonomy detail surface dataset")
    require(store_js, "autonomySummary: null,", label="autonomy summary state cache")
    require(app_js, "buildAutonomySummary", label="autonomy summary helper import")
    require(conversations_js, "buildAutonomySummary", label="autonomy summary helper dependency")
    require(conversations_js, "state.autonomySummary = normalizeAutonomySummary(", label="autonomy summary state hydration")
    require(conversations_js, "state.autonomySummary = null;", label="autonomy summary clear state")
    require(render_js, "dataset.sessionPresentation", label="session strip presentation dataset")
    require(render_js, "dataset.sessionTerminal", label="session strip terminal dataset")
    require(render_js, "sessionRail", label="session rail local expansion state")
    require(render_js, "transportChip", label="composer state transport chip helper")
    require(render_js, "phaseChip", label="composer state phase chip helper")
    require(render_js, "proposalChip", label="composer state proposal chip helper")
    require(render_js, "phaseDetailHint", label="phase detail hint helper")
    require(render_js, "shouldShowComposerLiveStrip", label="composer live strip visibility helper")
    require(render_js, "selectedThreadInlineSessionState", label="inline session visibility helper")
    require(render_js, "const degradedVisible =", label="inline degraded visibility helper")
    require(render_js, 'sessionIndicator.state === "reconnecting" || sessionIndicator.state === "polling"', label="inline degraded state scope")
    require(render_js, "if (inlineState.visible) {", label="composer strip suppression guard")
    require(render_js, "renderInlineSessionBlock", label="inline session workspace block helper")
    require(render_js, "summarizeInlineAutonomy", label="inline autonomy summary helper")
    require(render_js, "buildAutonomySummary", label="shared autonomy summary builder")
    require(render_js, 'data-live-autonomy="true"', label="inline autonomy DOM")
    require(render_js, 'data-autonomy-path-verdict="', label="inline autonomy path verdict dataset")
    require(render_js, 'data-autonomy-verifier-acceptability="', label="inline autonomy verifier dataset")
    require(render_js, 'data-autonomy-blocker-reason="', label="inline autonomy blocker dataset")
    require(render_js, 'data-autonomy-iteration="', label="inline autonomy iteration dataset")
    require(render_js, 'data-autonomy-source="', label="inline autonomy source dataset")
    require(render_js, 'data-autonomy-freshness-state="', label="inline autonomy freshness dataset")
    require(render_js, 'data-autonomy-fallback-allowed="', label="inline autonomy fallback dataset")
    require(render_js, 'data-autonomy-generated-at="', label="inline autonomy generated-at dataset")
    require(render_js, '<span>Iteration</span>', label="inline autonomy iteration copy")
    require(render_js, '<span>Path</span>', label="inline autonomy path copy")
    require(render_js, '<span>Signals</span>', label="inline autonomy signals copy")
    require(render_js, "INLINE_TERMINAL_RETENTION_MS = 12000", label="inline terminal retention window")
    require(render_js, "shouldRetainInlineTerminalPhase", label="inline terminal retention helper")
    require(render_js, "const { handoffVisible, degradedVisible, liveVisible, status, sessionIndicator } = inlineState;", label="inline session live visibility wiring")
    require(render_js, "if (!inlineState.visible) {", label="inline session unified visibility guard")
    require(render_js, 'data-selected-thread-live-block="${degradedVisible ? "false" : "true"}"', label="inline session workspace block DOM")
    require(render_js, 'data-selected-thread-degraded-block="${degradedVisible ? "true" : "false"}"', label="inline degraded session block DOM")
    require(render_js, 'data-live-block-owner="selected-thread"', label="inline session workspace block owner DOM")
    require(render_js, 'data-live-owned="${degradedVisible ? "false" : "true"}"', label="inline session workspace block ownership DOM")
    require(render_js, 'data-live-block-phase="', label="inline session workspace block phase DOM")
    require(render_js, 'data-live-block-reason="${escapeHtml(degradedVisible ? String(sessionIndicator.reason || "polling-fallback") : "healthy")}"', label="inline degraded session reason DOM")
    require(render_js, 'data-live-block-terminal="', label="inline session workspace block terminal DOM")
    require(render_js, 'sessionIndicator.reason === "session-rotation"', label="inline session rotation degraded copy")
    require(render_js, 'sessionIndicator.reason === "retrying"', label="inline retrying degraded copy")
    require(render_js, '${degradedVisible ? "" : autonomySummary}', label="inline degraded autonomy suppression")
    require(render_js, 'const retainedTerminalVisible = shouldRetainInlineTerminalPhase(', label="inline terminal retention wiring")
    require(render_js, '(!liveRun.terminal || retainedTerminalVisible);', label="inline terminal visibility guard")
    require(render_js, 'liveRun.terminal ? "terminal" : String(liveRun.state || "live")', label="inline terminal stage mapping")
    require(render_js, 'Date.now() - createdAtMs <= INLINE_TERMINAL_RETENTION_MS;', label="inline terminal retention deadline")
    require(render_js, "(liveRun.phase !== \"READY\" && liveRun.phase !== \"APPLIED\")", label="inline terminal phase scope")
    require(render_js, "latestAppendId > terminalAppendId", label="inline terminal next-append clear guard")
    require(render_js, "renderTranscriptLiveActivity", label="transcript live activity helper")
    require(render_js, "const transcriptLiveActivity = renderTranscriptLiveActivity(conversation, currentState, liveRun);", label="transcript live activity wiring")
    require(render_js, "if (inlineState.visible) {", label="transcript live activity suppression guard")
    require(render_js, "sessionTimelineEventModel", label="session timeline event model helper")
    require(render_js, "renderSessionTimelineEvent", label="session timeline event render helper")
    require(render_js, 'data-session-event="true"', label="session timeline event DOM")
    require(render_js, 'data-session-phase="${escapeHtml(model.phase)}"', label="session timeline event phase dataset")
    require(render_js, 'data-session-milestone="${escapeHtml(model.milestone)}"', label="session timeline event milestone dataset")
    require(render_js, 'data-session-verdict="${escapeHtml(model.verdict.toLowerCase())}"', label="session timeline event verdict dataset")
    require(render_js, 'const sessionEvent = renderSessionTimelineEvent(item);', label="session timeline event projection wiring")
    require(render_js, "if (sessionEvent) {", label="session timeline event branch")
    require(render_js, "transcriptLiveTone", label="transcript live activity tone helper")
    require(render_js, "composerActionHint", label="composer affordance hint helper")
    require(render_js, "threadMetaSummary", label="thread meta phase summary helper")
    require(render_js, "sessionProvenance", label="session provenance helper")
    require(render_js, "toggleSessionRail", label="session rail toggle helper")
    require(render_js, "dataset.sessionCollapsed", label="session strip collapsed dataset")
    require(render_js, 'if (!conversationId && !(threadTransition.active && threadTransition.targetConversationId)) {', label="composer strip idle clear branch")
    require(render_js, 'const ownerState = composerOwnerState(currentState, conversation);', label="composer strip owner helper wiring")
    require(render_js, 'const transportState = composerTransportState(currentState, conversation, liveRun, handoffState);', label="composer strip transport helper wiring")
    require(render_js, 'dom.sessionStrip.hidden = !sessionConversationId;', label="composer strip selected-target visibility")
    require(render_js, "const liveOwned =", label="composer live strip live ownership guard")
    require(render_js, 'dom.sessionStrip.dataset.liveOwned = liveOwned ? "true" : "false"', label="composer live strip ownership dataset")
    require(render_js, 'dom.sessionStrip.dataset.sessionOwner = liveOwned ? "selected-thread" : "none";', label="composer live strip selected-thread owner dataset")
    require(render_js, 'dom.sessionStrip.dataset.followState = transportState.owned ? "owned" : "idle";', label="composer strip follow-state dataset")
    require(render_js, 'dom.threadScroller.dataset.sessionOwner = liveOwned ? "selected-thread" : "none";', label="thread scroller selected-thread owner dataset")
    require(render_js, 'dom.sessionStripMeta.textContent = ownerState.target;', label="composer strip target copy")
    require(render_js, 'liveOwned && liveRun.phase && liveRun.phase !== "IDLE"', label="composer strip live phase chip guard")
    require(render_js, 'phaseChip(liveRun).tone', label="composer strip phase chip tone")
    require(render_js, 'phaseChip(liveRun).label', label="composer strip phase chip label")
    require(render_js, 'dom.sessionStripDetail.textContent = liveOwned ? compactPhaseDetailCopy(liveRun, ownerState.copy) : ownerState.copy;', label="composer strip live phase detail copy")
    require(render_js, 'reason: "thread-switch"', label="composer strip switch reason")
    require(render_js, 'reason: "polling-fallback"', label="composer strip polling fallback reason")
    require(render_js, "session-chip", label="session chip render markup")
    require(render_js, "function isSessionAuthorityEvent(event)", label="selected-thread session authority event helper")
    require(render_js, "function selectedThreadSseAuthorityEvent(conversation, currentState)", label="selected-thread SSE authority event selector")
    require(render_js, "function sessionAuthorityJobId(conversation, currentState)", label="selected-thread authority job id helper")
    require(render_js, "function sessionAuthorityEvents(conversation, currentState)", label="selected-thread authority event filter helper")
    require(render_js, 'String(event?.delivery_source || "").toLowerCase() !== "sse"', label="selected-thread SSE event provenance gate")
    require(render_js, "export function renderJobActivity(dom, conversation, currentJobId, jobPayload = null, currentState = null)", label="job activity current-state signature")
    require(render_js, "const selectedThreadSseOwned =", label="job activity selected-thread SSE ownership guard")
    require(render_js, "const liveRun = currentState ? deriveLiveRunState(conversation, currentState)", label="job activity live-run ownership source")
    require(render_js, "const jobId = sessionAuthorityJobId(conversation, currentState);", label="live run session authority job id")
    require(render_js, "const relevantEvents = sessionAuthorityEvents(conversation, currentState);", label="live run session authority event filter")
    require(render_js, "const liveAuthorityEvent = selectedThreadSseAuthorityEvent(conversation, currentState);", label="selected-thread authority event lookup")
    require(render_js, 'return liveAuthorityEvent;', label="healthy selected-thread authority event return")
    require(render_js, "const eventJobId = currentState", label="job activity event job id authority switch")
    require(render_js, "sessionAuthorityJobId(conversation, currentState)", label="job activity session authority job id")
    require(render_js, "const phase = selectedThreadSseOwned", label="job activity phase ownership switch")
    require(render_js, 'String(liveRun.phase || "IDLE").toUpperCase()', label="job activity SSE phase label")
    require(render_js, 'phaseLabel(jobPayload?.status || latestEvent?.status || "", latestEvent?.type || "")', label="job activity polling fallback phase label")
    require(render_js, "currentState.latestProposalJobId =", label="apply readiness from selected-thread live state")
    require(render_js, 'liveRun.state === "proposal-ready"', label="proposal-ready apply enable guard")
    require(render_js, "updateProposalButton(dom, currentState.latestProposalJobId);", label="apply button updated from selected-thread live state")
    require(render_js, 'renderJobActivity(dom, conversation, currentState.currentJobId || conversation.latest_job_id || "", null, currentState);', label="selected conversation job activity uses current state")
    require(render_js, "headerPhaseTone", label="thread header phase tone helper")
    require(render_js, "threadTitle", label="thread title header wiring")
    require(render_js, "threadPhaseChip", label="thread phase chip wiring")
    require(render_js, 'return { label: "SEND", tone: "thinking" };', label="compact send transport chip")
    require(render_js, 'return { label: "ACCEPTED", tone: "neutral" };', label="compact accepted handoff chip")
    require(render_js, 'return { label: "RECONNECT", tone: "warning" };', label="compact reconnect transport chip")
    require(render_js, 'return { label: "OPEN", tone: "neutral" };', label="compact connecting transport chip")
    require(render_js, 'return { label: "OFFLINE", tone: "danger" };', label="compact offline transport chip")
    require(render_js, 'return { label: "READY", tone: "healthy" };', label="compact ready chip")
    require(render_js, 'return { label: "APPLIED", tone: "healthy" };', label="compact applied chip")
    require(render_js, 'return { label: "BLOCKED", tone: "warning" };', label="compact blocked proposal chip")
    require(render_js, 'return "복구 중";', label="compact reconnect action hint")
    require(render_js, 'return "복구 필요";', label="compact offline action hint")
    require(render_js, 'return "연결 중";', label="compact connecting action hint")
    require(render_js, 'return "전송 중";', label="compact sending action hint")
    require(render_js, 'return "handoff 완료";', label="compact accepted action hint")
    require(render_js, 'return "HYPOTHESIS";', label="phase detail proposal hint")
    require(render_js, 'return "REVIEW SIGNAL";', label="phase detail review hint")
    require(render_js, 'return "VERIFY SIGNAL";', label="phase detail verify hint")
    require(render_js, 'return "AUTO APPLY";', label="phase detail auto-apply hint")
    require(render_js, 'return "READY TO APPLY";', label="phase detail proposal-ready hint")
    require(render_js, 'return "APPLY COMPLETE";', label="phase detail applied hint")
    require(render_js, 'return "응답 생성";', label="compact generating action hint")
    require(render_js, 'return "실행 중";', label="compact live execution action hint")
    require(render_js, 'return "계속 입력";', label="compact live action hint")
    require(render_js, 'return "입력 가능";', label="compact idle action hint")
    require(render_js, '"RECONNECT"', label="degraded stream provenance label")
    require(render_js, '"OPEN"', label="connecting stream provenance label")
    require(render_js, '"OFFLINE"', label="offline stream provenance label")
    require(render_js, 'dom.sessionStripToggle.hidden = true', label="session strip toggle hidden")
    require(render_js, 'dom.sendRequestButton.textContent = status === "live" || presentation === "sending" ? "추가 지시 보내기" : "메시지 보내기"', label="contextual send copy")
    require(render_js, 'dom.applyProposalButton.textContent = liveRun.state === "proposal-ready" ? "지금 제안 적용" : "제안 적용"', label="contextual apply copy")
    require(render_js, "dataset.liveRunState", label="live run state dataset")
    require(render_js, "dataset.liveRunPhase", label="live run phase dataset")
    require(render_js, "dataset.liveRunSource", label="live run source dataset")
    require(render_js, "dataset.followState", label="follow-state dataset")
    require(render_js, 'data-live-activity-turn="true"', label="transcript live activity DOM")
    require(render_js, 'data-live-owned="true"', label="transcript live activity ownership DOM")
    require(render_js, 'data-append-source="sse-live-activity"', label="transcript live activity provenance DOM")
    require(render_js, '${autonomySummary}', label="transcript live activity autonomy projection")
    require(render_js, "selected thread", label="transcript live activity selected-thread copy")
    require(render_js, "!inlineState.selectedThreadSseOwned", label="transcript live activity selected-thread ownership guard")
    require(render_js, "inlineState.handoffVisible", label="transcript live activity handoff suppression guard")
    require(render_js, "inlineState.degradedVisible", label="transcript live activity degraded suppression guard")
    require(render_js, "syncJumpToLatest", label="jump-to-latest sync helper")
    require(render_js, "updateLiveFollowFromScroll", label="live follow scroll helper")
    require(render_js, "jumpToLatest", label="jump-to-latest action helper")
    require(render_js, "currentState.liveFollow", label="live follow state wiring")
    require(render_js, "lastSeenAppendId", label="live follow seen append cursor")
    require(render_js, "pendingAppendCount", label="live follow unseen append count")
    require(render_js, "followRenderSource", label="jump-to-latest render source dataset")
    require(render_js, 'const liveOwned =', label="follow control live-owned guard")
    require(render_js, 'const terminalIdle = String(dom.threadScroller?.dataset.sessionTerminal || "false") === "true";', label="follow control terminal-idle guard")
    require(render_js, 'const detached = !Boolean(liveFollow.isFollowing);', label="follow control detached-state guard")
    require(render_js, 'const hasBacklog = unseenCount > 0;', label="follow control backlog guard")
    require(render_js, 'const pausedVisible = liveOwned && detached && !hasBacklog;', label="follow control paused visibility guard")
    require(render_js, 'const followState = hasBacklog ? "new" : "paused";', label="follow control state mapping")
    require(render_js, 'const isVisible = Boolean(liveOwned && detached);', label="follow control visibility mapping")
    require(render_js, 'dom.jumpToLatestButton.dataset.followOwned = liveOwned ? "selected-thread" : "none";', label="follow control owner dataset")
    require(render_js, 'dom.jumpToLatestButton.dataset.followState = isVisible ? followState : "hidden";', label="follow control state dataset")
    require(render_js, 'dom.jumpToLatestButton.dataset.followCount = String(isVisible ? unseenCount : 0);', label="follow control unseen count dataset")
    require(render_js, 'stateLabel = followState === "new" ? "NEW" : "PAUSED";', label="follow control explicit state labels")
    require(render_js, 'detailLabel =', label="follow control detail label")
    require(render_js, "새 live append", label="follow control new copy")
    require(render_js, "live follow paused", label="follow control paused copy")
    require(render_js, "data-append-source", label="append provenance attribute")
    require(render_js, "dataset.streamState = status", label="stream-state dataset")
    require(render_js, "dataset.attachMode = attachMode", label="attach-mode dataset")
    require(render_js, "dataset.bootstrapVersion = bootstrapVersion", label="bootstrap-version dataset")
    require(render_js, "dataset.resumeMode = resumeMode", label="resume-mode dataset")
    require(render_js, "dataset.resumeCursor = String(resumeCursor)", label="resume-cursor dataset")
    require(render_js, "dataset.phaseValue", label="phase value dataset")
    require(render_js, "dataset.phaseAuthoritative", label="phase authoritative dataset")
    require(render_js, "dataset.phaseProvenance", label="phase provenance dataset")
    require(render_js, 'ownerState.state === "switching" ? "UNKNOWN"', label="switching phase value reset")
    require(render_js, '"thread-transition"', label="switching phase provenance")
    require(render_js, "dataset.renderSource = lastRenderSource", label="render-source dataset")
    require(conversations_js, 'dom.threadScroller.dataset.pendingConversationId = conversationId', label="thread switch pending marker")
    require(conversations_js, "state.currentConversationId && state.currentConversationId !== conversationId", label="thread switch clear guard")
    require(store_js, "threadTransition", label="thread transition state")
    require(store_js, "appendStream", label="append stream state")
    require(store_js, "pendingOutgoing", label="pending outgoing state")
    require(store_js, "assistantCreatedAt", label="assistant placeholder pending timestamp state")
    require(store_js, "baselineAppendId", label="pending handoff baseline append id state")
    require(store_js, "isAppendStreamConnected", label="append stream connection helper")
    require(store_js, "liveFollow", label="live follow state")
    require(store_js, "lastSeenAppendId", label="live follow seen append state")
    require(store_js, "pendingAppendCount", label="live follow unseen append state")
    require(index_html, 'id="session-strip"', label="session strip DOM")
    require(index_html, 'id="session-strip-state"', label="session strip state DOM")
    require(index_html, 'id="session-strip-meta"', label="session strip meta DOM")
    require(index_html, 'id="session-strip-detail"', label="session strip detail DOM")
    require(index_html, 'id="composer-owner-row"', label="composer owner row DOM")
    require(index_html, 'id="composer-owner-state"', label="composer owner state DOM")
    require(index_html, 'id="composer-owner-target"', label="composer owner target DOM")
    require(index_html, 'id="composer-owner-copy"', label="composer owner copy DOM")
    require(index_html, 'data-thread-header="conversation"', label="conversation-first thread header DOM")
    require(index_html, 'id="thread-title"', label="thread title DOM")
    require(index_html, 'id="thread-phase-chip"', label="thread phase chip DOM")
    require(index_html, 'id="session-summary-row"', label="session summary row DOM")
    require(index_html, 'id="recent-thread-rail"', label="recent-thread rail DOM")
    require(index_html, 'id="recent-thread-rail-list"', label="recent-thread rail list DOM")
    require(index_html, 'id="session-live-indicator"', label="header live-session indicator DOM")
    require(index_html, 'data-live-session-source="none"', label="header live-session source default")
    require(index_html, 'data-live-session-owned="false"', label="header live-session ownership default")
    require(index_html, 'data-live-session-reason="idle"', label="header live-session reason default")
    require(index_html, 'id="session-summary-scope"', label="session summary scope DOM")
    require(index_html, 'id="session-summary-path"', label="session summary path DOM")
    require(index_html, 'id="session-summary-state"', label="session summary state DOM")
    require(index_html, 'id="session-summary-copy"', label="session summary copy DOM")
    require(index_html, 'id="session-strip-toggle"', label="session strip toggle DOM")
    require(index_html, 'data-activity-bar="composer-adjacent"', label="composer-adjacent activity bar DOM")
    require(index_html, 'class="composer-toolbar"', label="chat-style composer toolbar DOM")
    require(index_html, 'class="composer-send-primary"', label="primary send button DOM")
    require(index_html, "composer-secondary-action", label="secondary composer action DOM")
    require(index_html, 'id="composer-utility-menu"', label="composer utility menu DOM")
    require(index_html, 'id="composer-utility-toggle"', label="composer utility toggle DOM")
    require(index_html, 'id="composer-utility-cluster"', label="composer utility cluster DOM")
    require(index_html, 'data-composer-layout="chat-first"', label="chat-first composer footer DOM")
    require(index_html, 'data-composer-utility-panel="compact"', label="compact composer utility panel DOM")
    require(index_html, 'class="toggle inline composer-utility-toggle"', label="composer utility toggle DOM")
    require(index_html, 'id="conversation-footer-dock"', label="conversation footer dock DOM")
    require(index_html, 'id="active-session-row"', label="active session row DOM")
    require(index_html, 'id="active-session-owner"', label="active session owner DOM")
    require(index_html, 'id="active-session-state"', label="active session state DOM")
    require(index_html, 'id="active-session-follow"', label="active session follow DOM")
    require(index_html, 'id="active-session-title"', label="active session title DOM")
    require(index_html, 'id="active-session-meta"', label="active session meta DOM")
    require(index_html, 'data-active-session-owned="false"', label="active session owned default")
    require(index_html, 'data-active-session-source="none"', label="active session source default")
    require(index_html, 'data-active-session-phase="IDLE"', label="active session phase default")
    require(index_html, 'data-active-session-unseen-count="0"', label="active session unseen default")
    require(index_html, 'data-footer-dock="session-composer"', label="footer dock mode DOM")
    require(index_html, 'data-session-workspace="conversation-first"', label="conversation-first session workspace DOM")
    require(index_html, 'id="jump-to-latest"', label="jump-to-latest DOM")
    require(index_html, 'class="jump-to-latest-chip"', label="jump-to-latest chip DOM")
    require(index_html, 'class="jump-to-latest-copy"', label="jump-to-latest copy DOM")
    require(index_html, 'id="autonomy-detail"', label="secondary panel autonomy detail DOM")
    require(index_html, 'id="autonomy-detail-meta"', label="secondary panel autonomy detail meta DOM")
    require(index_html, 'id="secondary-panel"', label="secondary panel DOM")
    require(index_html, 'data-secondary-panel-mode="compact-sidecar"', label="compact side panel DOM")
    require(index_html, 'id="secondary-panel-toggle"', label="secondary panel toggle DOM")
    require(index_html, 'id="secondary-panel-close"', label="secondary panel close DOM")
    require(index_html, 'id="nav-sheet-toggle"', label="mobile nav toggle DOM")
    require(index_html, 'id="nav-sheet-close"', label="mobile nav close DOM")
    require(index_html, 'id="nav-sheet-scrim"', label="mobile nav scrim DOM")
    require(index_html, 'id="nav-sheet"', label="mobile nav sheet DOM")
    require(index_html, 'data-mobile-surface="sheet"', label="mobile nav sheet surface marker")
    require(index_html, 'data-mobile-nav-priority="conversations"', label="mobile nav conversation priority DOM")
    require(index_html, 'data-nav-primary="threads"', label="mobile nav threads-first section DOM")
    require(index_html, 'data-nav-secondary="ops"', label="mobile nav secondary operator section DOM")
    require(index_html, 'id="selected-app-summary"', label="selected app summary DOM")
    require(index_html, 'data-sidebar-app-summary="compact"', label="compact app summary DOM")
    require(index_html, 'data-primary-surface="conversation"', label="active conversation primary surface DOM")
    require(index_html, 'aria-controls="nav-sheet"', label="mobile nav toggle controls DOM")
    require(index_html, 'aria-expanded="false"', label="mobile nav closed default DOM")
    require(index_html, 'id="nav-ops-section"', label="mobile operator section DOM")
    require(index_html, 'id="nav-ops-summary"', label="mobile operator summary DOM")
    require(index_html, 'id="thread-scroller" class="thread-scroller" tabindex="-1"', label="conversation surface focus target DOM")
    require(app_js, "internalConversationAppendStreamUrl", label="controller dependency wiring")
    require(app_js, "showPendingOutgoing", label="pending outgoing submit wiring")
    require(app_js, "showPendingAssistant", label="pending assistant submit wiring")
    require(app_js, "clearPendingOutgoing", label="pending outgoing clear wiring")
    require(app_js, "isSelectedThreadSessionOwned", label="submit path selected-thread session ownership helper wiring")
    require(app_js, 'if (!isSelectedThreadSessionOwned(state, conversationId)) {', label="submit path degraded-only eager poll guard")
    require(app_js, "} else {\n      jobController.stopPolling();\n    }", label="submit path sse-owned polling suppression")
    require_absent(app_js, "jobController.stopPolling();\n    await jobController.pollCurrentState();\n    jobController.ensurePollingForJob();", label="legacy unconditional eager submit poll")
    require(app_js, "setNavigationOpen", label="mobile nav state helper")
    require(app_js, "isPhoneViewport", label="phone breakpoint helper")
    require(app_js, "focusPrimaryNavAction", label="mobile nav primary action focus helper")
    require(app_js, "returnFocusToConversationSurface", label="mobile nav conversation return focus helper")
    require(app_js, "syncMobileWorkspaceMode", label="mobile nav mode helper")
    require(app_js, 'dom.secondaryPanelToggle.setAttribute("aria-expanded", isOpen ? "true" : "false");', label="secondary panel aria expanded sync")
    require(app_js, 'document.body.dataset.mobileNavMode = isPhoneViewport() ? "drawer" : "desktop"', label="mobile nav mode dataset")
    require(app_js, 'document.body.dataset.mobileWorkspace = isOpen ? "navigation" : "conversation"', label="mobile workspace state helper")
    require(app_js, 'dom.navOpsSection.open = false;', label="mobile operator section collapse on phone")
    require(app_js, 'dom.navSheetToggle.setAttribute("aria-expanded", isOpen ? "true" : "false")', label="mobile nav toggle expanded state")
    require(app_js, 'navSheet.setAttribute("aria-hidden", isOpen ? "false" : "true")', label="mobile nav sheet aria state")
    require(app_js, "syncNavOpsSection", label="mobile operator section state helper")
    require(app_js, "dom.navOpsSection.open = false;", label="operator section collapsed by default")
    require(app_js, 'primaryAction.focus({ preventScroll: true })', label="mobile nav focuses first thread action")
    require(app_js, 'preferredTarget.focus({ preventScroll: true })', label="mobile conversation surface focus return")
    require(app_js, "updateLiveFollowFromScroll", label="live follow scroll event wiring")
    require(app_js, "jumpToLatest", label="jump-to-latest button wiring")
    require(app_js, "reengageLiveFollowFromComposer", label="composer reengages live follow helper")
    require(app_js, 'dom.requestTextInput.addEventListener("focus", reengageLiveFollowFromComposer)', label="composer focus reengages live follow")
    require(app_js, 'dom.requestTextInput.addEventListener("input", reengageLiveFollowFromComposer)', label="composer input reengages live follow")
    require(app_js, "toggleSessionRail", label="session rail toggle wiring")
    require(app_js, 'dom.recentThreadRailList?.addEventListener("click", async (event) => {', label="recent-thread rail click wiring")
    require(app_js, "setSecondaryPanelOpen", label="secondary panel state helper")
    require(app_js, "setComposerUtilityOpen", label="composer utility state helper")
    require(app_js, "syncSendButtonState", label="composer send availability helper")
    require(app_js, 'dom.sendRequestButton.dataset.sendBusy = "true";', label="composer send busy start")
    require(app_js, 'dom.sendRequestButton.dataset.sendBusy = "false";', label="composer send busy end")
    require(app_js, 'dom.sendRequestButton?.dataset.composerBlocked === "true"', label="composer blocked guard")
    require(app_js, 'dom.composerUtilityMenu.dataset.composerUtilityOpen = isOpen ? "true" : "false";', label="composer utility dataset state")
    require(app_js, 'dom.composerUtilityCluster.hidden = !isOpen;', label="composer utility hidden state")
    require(app_js, 'dom.composerUtilityToggle.setAttribute("aria-expanded", isOpen ? "true" : "false");', label="composer utility aria state")
    require(app_js, 'window.innerWidth > 860', label="mobile nav resize reset")
    require(deployed_console_sh, 'WORKSPACE_APP_ID="${WORKSPACE_APP_ID:-factory-runtime}"', label="workspace gate app default")
    require(deployed_console_sh, 'python3 ./scripts/verify_deployed_workspace_gate.py', label="deployed workspace gate wiring")
    require(api_js, 'sessionId: option.dataset.sessionId || ""', label="selected app session id API wiring")
    require(store_js, "appSession", label="selected app session state")
    require(deployed_workspace_py, 'DEFAULT_REQUEST_TEXT = (', label="workspace gate default request")
    require(deployed_workspace_py, 'goal.proposal.phase.started', label="workspace gate proposal phase assertion")
    require(deployed_workspace_py, 'goal.review.phase.started', label="workspace gate review phase assertion")
    require(deployed_workspace_py, 'goal.verify.phase.started', label="workspace gate verify phase assertion")
    require(deployed_workspace_py, "proposal.ready", label="workspace gate proposal ready assertion")
    require(deployed_workspace_py, 'conversation.append', label="workspace gate sse append assertion")
    require(deployed_workspace_py, "phaseChip", label="workspace gate browser-visible phase chip assertion")
    require(deployed_workspace_py, "dataset.liveRunPhase", label="workspace gate live phase dataset assertion")
    require(deployed_workspace_py, "dataset.streamState", label="workspace gate transport dataset assertion")
    require(deployed_workspace_py, "dataset.attachMode", label="workspace gate attach-mode dataset assertion")
    require(deployed_workspace_py, "dataset.bootstrapVersion", label="workspace gate bootstrap-version dataset assertion")
    require(deployed_workspace_py, "load_playwright", label="workspace gate playwright loader")
    require(deployed_workspace_py, "assert_browser_runtime_surface", label="workspace gate browser runtime helper")
    require(deployed_workspace_py, "browser_snapshot_script", label="workspace gate browser snapshot helper")
    require(deployed_workspace_py, 'VERIFY_BROWSER_RUNTIME', label="workspace gate browser runtime env toggle")
    require(deployed_workspace_py, 'page.fill("#request-text", request_text)', label="workspace gate browser composer submission")
    require(deployed_workspace_py, 'window.__verifyForceDegrade = true;', label="workspace gate browser degrade trigger")
    require(deployed_workspace_py, 'data-selected-thread-degraded-block="true"', label="workspace gate browser degraded inline assertion")
    require(deployed_workspace_py, 'data-thread-transition="loading"', label="workspace gate browser switch placeholder assertion")
    require(deployed_workspace_py, '.timeline-empty', label="workspace gate browser empty-state selector")
    require(deployed_workspace_py, "#thread-scroller", label="workspace gate browser thread scroller assertion")
    require(deployed_workspace_py, "document.querySelectorAll('[data-thread-transition=\"loading\"]').length === 1", label="workspace gate browser single switch placeholder assertion")
    require(deployed_workspace_py, 'threadScroller.dataset.sessionOwner !== "selected-thread"', label="workspace gate browser clears old live ownership on switch")
    require(deployed_workspace_py, 'follow.dataset.followOwned !== "selected-thread"', label="workspace gate browser clears follow ownership on switch")
    require(deployed_workspace_py, 'summary.dataset.liveSessionOwned === "false"', label="workspace gate browser clears header ownership on switch")
    require(deployed_workspace_py, 'entry => String(entry.url || "").includes("/api/jobs/")', label="workspace gate browser switch job fetch selector")
    require(deployed_workspace_py, "jobFetches.length === 0", label="workspace gate browser no job fetch on switch")
    require(deployed_workspace_py, 'liveIndicator.hidden', label="workspace gate browser hides header live indicator on switch")
    require(deployed_workspace_py, 'composerOwnerRow.hidden', label="workspace gate browser switching composer owner row hidden")
    require(deployed_workspace_py, 'composerOwnerRow.dataset.composerOwnerMerged === "true"', label="workspace gate browser switching composer owner merged")
    require(deployed_workspace_py, '!healthyBlock', label="workspace gate browser removes healthy inline block on switch")
    require(deployed_workspace_py, 'item.event === "session.bootstrap"', label="workspace gate browser bootstrap event assertion")
    require(deployed_workspace_py, 'conversationFetches.length === 0', label="workspace gate browser no snapshot fetch assertion")
    require(deployed_workspace_py, 'id="session-live-indicator"', label="workspace gate header live-session DOM assertion")
    require(deployed_workspace_py, "selectedThreadLiveSessionIndicator", label="workspace gate header live-session helper assertion")
    require(deployed_workspace_py, "dataset.liveSessionState", label="workspace gate header live-session dataset assertion")
    require(api_runtime_context_py, '"autonomy_summary": dict(conversation.get("autonomy_summary") or {})', label="bootstrap autonomy summary envelope")
    require(api_runtime_context_py, 'conversation["autonomy_summary"] = self.autonomy_summary_payload(', label="conversation snapshot autonomy summary envelope")
    require(api_runtime_context_py, '"freshness_state": "stale-or-missing"', label="autonomy stale-or-missing marker")
    require(api_runtime_context_py, '"fallback_allowed": fallback_allowed,', label="autonomy fallback allowed field")
    require(api_runtime_context_py, '"source": source,', label="autonomy summary source field")
    require(api_runtime_context_py, '"generated_at": generated_at,', label="autonomy summary generated-at field")
    require(api_routes_py, "return context.conversation_snapshot_payload(conversation_id)", label="conversation snapshot route autonomy envelope")
    require(deployed_workspace_py, 'codex.exec.retrying', label="workspace gate retry degradation assertion")
    require(deployed_workspace_py, "unexpected session rotation", label="workspace gate session rotation guard")
    require(styles_css, 'body[data-nav-open="true"] .sidebar', label="mobile nav drawer CSS")
    require(styles_css, 'body[data-mobile-nav-mode="drawer"] .sidebar[data-mobile-nav-priority="conversations"] .sidebar-primary-nav', label="mobile nav drawer mode CSS")
    require(styles_css, 'body[data-mobile-workspace="conversation"] .main-stage', label="conversation-first mobile surface CSS")
    require(styles_css, "touch-action: none;", label="mobile nav open touch lock CSS")
    require(styles_css, 'body[data-secondary-panel-open="true"] .desktop-shell', label="desktop secondary panel layout CSS")
    require(styles_css, "grid-template-columns: 15rem minmax(0, 1fr);", label="desktop two-pane shell width")
    require(styles_css, "grid-template-columns: 13.5rem minmax(0, 1fr);", label="desktop two-pane shell width at medium desktop")
    require(styles_css, ".autonomy-detail-card", label="secondary panel autonomy detail card CSS")
    require(styles_css, ".secondary-panel", label="secondary panel CSS")
    require(styles_css, "position: fixed;", label="desktop secondary panel overlay positioning")
    require(styles_css, "width: min(18.5rem, calc(100vw - 2rem));", label="desktop secondary panel overlay width")
    require(styles_css, ".thread-title-row", label="thread title row CSS")
    require(styles_css, ".session-summary-row", label="session summary row CSS")
    require(styles_css, ".recent-thread-rail", label="recent-thread rail CSS")
    require(styles_css, ".recent-thread-rail-list", label="recent-thread rail list CSS")
    require(styles_css, ".recent-thread-chip", label="recent-thread chip CSS")
    require(styles_css, '.recent-thread-chip[data-thread-state="switching"] .recent-thread-token[data-recent-thread-state]', label="recent-thread switching chip CSS")
    require(styles_css, '.recent-thread-chip[data-live-owner="true"] .recent-thread-token[data-recent-thread-owner]', label="recent-thread owner chip CSS")
    require(styles_css, '.recent-thread-chip[data-live-owner-state="new"] .recent-thread-token[data-recent-thread-follow]', label="recent-thread new follow chip CSS")
    require(styles_css, ".session-live-indicator", label="header live-session indicator CSS")
    require(styles_css, '.session-live-indicator[data-live-session-tone="healthy"]', label="header live-session healthy CSS")
    require(styles_css, '.session-live-indicator[data-live-session-tone="warning"]', label="header live-session warning CSS")
    require(styles_css, '.session-live-indicator[data-live-session-tone="danger"]', label="header live-session danger CSS")
    require(styles_css, ".session-summary-chip", label="session summary chip CSS")
    require(styles_css, ".session-summary-copy", label="session summary copy CSS")
    require(styles_css, '.session-summary-row[data-summary-path="switching"] .session-summary-chip[data-summary-chip="path"]', label="summary switching chip CSS")
    require(styles_css, '.session-summary-row[data-summary-path="handoff"] .session-summary-chip[data-summary-chip="path"]', label="summary handoff chip CSS")
    require(styles_css, '.session-summary-row[data-summary-path="sse"] .session-summary-chip[data-summary-chip="path"]', label="summary sse chip CSS")
    require(styles_css, ".thread-phase-chip", label="thread phase chip CSS")
    require(styles_css, ".thread-sidecar", label="thread sidecar CSS")
    require(styles_css, "width: min(100%, 54rem);", label="dominant conversation column width")
    require(styles_css, ".conversation-card-live", label="conversation card live badge CSS")
    require(styles_css, ".conversation-card-marker", label="conversation card selected badge CSS")
    require(styles_css, ".conversation-card-session", label="conversation card session badge CSS")
    require(styles_css, '.conversation-card[data-live-owner="true"]', label="selected live owner card CSS")
    require(styles_css, ".conversation-card-live-owner-row", label="selected live owner row CSS")
    require(styles_css, ".conversation-card-live-detail", label="selected live detail CSS")
    require(styles_css, ".conversation-card-live-follow", label="selected live follow CSS")
    require(styles_css, ".conversation-card-tags", label="conversation card session tag row CSS")
    require(styles_css, ".conversation-card-preview", label="conversation card preview CSS")
    require(styles_css, ".active-session-row", label="active session row CSS")
    require(styles_css, ".active-session-chip", label="active session chip CSS")
    require(styles_css, ".active-session-title", label="active session title CSS")
    require(styles_css, ".active-session-meta", label="active session meta CSS")
    require(styles_css, '.active-session-row[data-active-session-state="paused"] .active-session-chip[data-active-chip="state"]', label="active session paused chip CSS")
    require(styles_css, '.active-session-row[data-active-session-follow="live"] .active-session-chip[data-active-chip="follow"]', label="active session live follow chip CSS")
    require(styles_css, '.conversation-card-preview[data-preview-lines="1"]', label="single-line conversation preview CSS")
    require(styles_css, '.conversation-card[data-thread-state="active"] .conversation-card-live', label="active card state CSS")
    require(styles_css, '.conversation-card[data-thread-state="active"] .conversation-card-session', label="active session marker CSS")
    require(styles_css, '.conversation-card[data-thread-state="review"] .conversation-card-live', label="review card state CSS")
    require(styles_css, '.conversation-card[data-thread-state="verify"] .conversation-card-live', label="verify card state CSS")
    require(styles_css, '.conversation-card[data-thread-state="ready"] .conversation-card-live', label="ready card state CSS")
    require(styles_css, '.conversation-card[data-live-owner="true"] .conversation-card-marker', label="selected live owner marker CSS")
    require(styles_css, '.conversation-card[data-live-owner="true"] .conversation-card-session', label="selected live owner session CSS")
    require(styles_css, '.conversation-card[data-live-owner-state="handoff"] .conversation-card-marker', label="selected handoff owner marker CSS")
    require(styles_css, '.conversation-card[data-live-owner-state="new"] .conversation-card-marker', label="selected new owner marker CSS")
    require(styles_css, '.conversation-card[data-live-owner-state="paused"] .conversation-card-marker', label="selected paused owner marker CSS")
    require(styles_css, '.conversation-card-live-owner-row[data-live-owner-state="handoff"] .conversation-card-live-follow', label="selected handoff follow chip CSS")
    require(styles_css, '.conversation-card-live-owner-row[data-live-owner-state="new"] .conversation-card-live-follow', label="selected new follow chip CSS")
    require(styles_css, '.conversation-card-live-owner-row[data-live-owner-state="paused"] .conversation-card-live-follow', label="selected paused follow chip CSS")
    require_absent(conversations_js, "메시지 handoff 중", label="legacy selected row handoff prose")
    require_absent(conversations_js, "첫 응답 대기", label="legacy selected row accepted prose")
    require_absent(conversations_js, "선택된 세션 연결 중", label="legacy selected row connecting prose")
    require_absent(conversations_js, "선택된 세션 복구 중", label="legacy selected row reconnect prose")
    require(styles_css, '.conversation-card[data-thread-state="failed"] .conversation-card-live', label="failed card state CSS")
    require(styles_css, '.conversation-card[data-thread-state="idle"] .conversation-card-live', label="idle card state CSS")
    require(styles_css, ".timeline-item.message.user.pending-local", label="pending local message CSS")
    require(styles_css, ".timeline-item.message.assistant.pending-assistant", label="pending assistant message CSS")
    require(styles_css, ".timeline-item.live-activity", label="transcript live activity CSS")
    require(styles_css, ".session-inline-block", label="inline session block CSS")
    require(styles_css, ".session-inline-chip", label="inline session chip CSS")
    require(styles_css, ".session-inline-meta", label="inline session meta CSS")
    require(styles_css, ".timeline-live-row", label="transcript live activity chip row CSS")
    require(styles_css, ".timeline-item.session-event", label="session timeline event CSS")
    require(styles_css, '.timeline-item.session-event[data-session-verdict="disqualifying"]', label="session timeline disqualifying CSS")
    require(styles_css, ".timeline-live-chip", label="transcript live activity chip CSS")
    require(styles_css, ".session-strip", label="session strip CSS")
    require(styles_css, ".composer-owner-row", label="composer owner row CSS")
    require(styles_css, ".composer-owner-chip", label="composer owner chip CSS")
    require(styles_css, ".composer-owner-target", label="composer owner target CSS")
    require(styles_css, '.composer-send-primary[data-composer-blocked="true"]', label="composer blocked send CSS")
    require(styles_css, '.session-strip[data-live-owned="true"]', label="composer live strip active CSS")
    require(styles_css, '.session-strip[data-stream-state="reconnecting"]', label="composer reconnecting strip CSS")
    require(styles_css, '.session-strip[data-stream-state="offline"]', label="composer offline strip CSS")
    require(styles_css, '.session-strip[data-stream-state="connecting"]', label="composer connecting strip CSS")
    require(styles_css, ".session-activity-bar", label="composer activity bar CSS")
    require(styles_css, ".session-chip", label="composer state chip CSS")
    require(styles_css, "flex-wrap: wrap;", label="composer activity inline wrap CSS")
    require(styles_css, "justify-content: flex-start;", label="composer activity inline alignment CSS")
    require(styles_css, ".session-strip-toggle {\n  min-width: 5.8rem;\n  margin-left: auto;", label="composer activity toggle push CSS")
    require(styles_css, ".session-strip-meta,\n.session-strip-detail {\n  color: var(--muted);", label="composer activity inline metadata CSS")
    require(styles_css, "display: inline-flex;", label="composer activity inline chip display CSS")
    require_absent(styles_css, ".session-strip-main", label="legacy composer activity main CSS")
    require_absent(styles_css, ".session-strip-side", label="legacy composer activity side CSS")
    require(render_js, 'const stage = degradedVisible', label="inline degraded stage mapping")
    require(render_js, 'const phaseLabel = degradedVisible', label="inline degraded phase mapping")
    require(render_js, 'const sourceLabel = degradedVisible ? String(sessionIndicator.source || "polling") : handoffVisible ? "handoff" : "sse";', label="inline degraded source mapping")
    require(render_js, "const renderedItems = items", label="transcript render item join")
    require(render_js, 'if (!items.length && !inlineSessionBlock && !transcriptLiveActivity) {', label="transcript empty-state live activity guard")
    require(render_js, 'dom.conversationTimeline.innerHTML = renderedItems + transcriptLiveActivity + inlineSessionBlock;', label="transcript tail live activity render")
    require_absent(render_js, 'dom.conversationTimeline.innerHTML = inlineSessionBlock + items', label="legacy inline block prepended render")
    require_absent(render_js, "In Flight Assistant", label="duplicate accepted status block copy")
    require_absent(render_js, 'return { label: "GENERATING", tone: "neutral" };', label="legacy generating handoff chip")
    require(styles_css, ".session-strip-draft", label="composer activity draft CSS")
    require(styles_css, ".composer-toolbar", label="chat-style composer toolbar CSS")
    require(styles_css, ".composer-footer", label="chat-first composer footer CSS")
    require(styles_css, ".composer-send-primary", label="primary send button CSS")
    require(styles_css, ".composer-utility-menu", label="composer utility menu CSS")
    require(styles_css, ".composer-utility-toggle-button", label="composer utility toggle button CSS")
    require(styles_css, ".composer-secondary-action", label="secondary composer action CSS")
    require(styles_css, ".composer-utility-cluster", label="composer utility cluster CSS")
    require(styles_css, ".composer-utility-toggle", label="composer utility toggle CSS")
    require(styles_css, ".composer-hint-compact", label="compact composer hint CSS")
    require(styles_css, ".sidebar-primary-nav", label="mobile conversation-first nav section CSS")
    require(styles_css, ".sidebar-app-summary", label="compact app summary CSS")
    require(styles_css, ".sidebar-app-summary-copy", label="compact app summary copy CSS")
    require(styles_css, ".sidebar-ops-details", label="mobile operator section CSS")
    require(styles_css, ".nav-ops-summary", label="mobile operator summary CSS")
    require(styles_css, ".nav-ops-content", label="mobile operator content CSS")
    require(styles_css, '.sidebar[data-mobile-nav-priority="conversations"] .sidebar-primary-nav[data-nav-primary="threads"]', label="mobile nav primary section priority CSS")
    require(styles_css, '.sidebar[data-mobile-nav-priority="conversations"] .sidebar-ops-details[data-nav-secondary="ops"]', label="mobile nav secondary section CSS")
    require(styles_css, ".sidebar-ops-details[open] .nav-ops-summary::after", label="mobile operator summary state CSS")
    require(styles_css, "order: 1;", label="conversation rail primary order CSS")
    require(styles_css, "order: 2;", label="operator rail secondary order CSS")
    require(styles_css, ".jump-to-latest", label="jump-to-latest CSS")
    require(styles_css, ".jump-to-latest-chip", label="jump-to-latest chip CSS")
    require(styles_css, ".jump-to-latest-copy", label="jump-to-latest copy CSS")
    require(styles_css, '.jump-to-latest[data-follow-state="new"] .jump-to-latest-chip', label="jump-to-latest new state CSS")
    require(styles_css, '.jump-to-latest[data-follow-state="paused"] .jump-to-latest-chip', label="jump-to-latest paused state CSS")
    require(styles_css, ".timeline-transition", label="thread transition CSS")
    require(styles_css, ".timeline-transition-chip", label="thread transition chip CSS")
    require(styles_css, "position: sticky;", label="sticky footer CSS")
    require(styles_css, "env(safe-area-inset-bottom)", label="safe-area footer padding CSS")
    require(styles_css, ".mobile-nav-toggle", label="mobile nav button CSS")
    require(styles_css, ".thread-scroller:focus-visible", label="conversation surface focus ring CSS")
    require_absent(index_html, 'id="conversation-live-status"', label="legacy live badge DOM")
    require_absent(index_html, 'id="live-run-row"', label="legacy live run row DOM")
    require_absent(index_html, 'id="append-stream-strip"', label="legacy append stream DOM")
    require_absent(index_html, 'id="autonomy-context-strip"', label="header autonomy strip DOM")
    require_absent(index_html, 'id="hero-conversation-state"', label="header conversation status DOM")
    require_absent(index_html, 'id="hero-job-state"', label="header job status DOM")
    require_absent(index_html, 'id="hero-app-name"', label="legacy app-centric header title DOM")
    require_absent(index_html, "<h3>메시지 보내기</h3>", label="prose-heavy composer heading DOM")
    require_absent(index_html, "sidebar-inspector", label="legacy sidebar inspector")
    require_absent(index_html, "sidebar-footer", label="legacy sidebar footer")
    require_absent(index_html, 'class="autonomy-rail"', label="legacy standalone autonomy rail DOM")
    print("ok: ops desktop secondary panel, footer dock, session strip, append SSE wiring, and mobile nav drawer are present")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except AssertionError as error:
        print(f"verification failed: {error}", file=sys.stderr)
        raise SystemExit(1)
